'use client';
import Link from 'next/link';
import { SmokeText } from '@/components/SmokeText';
import { RabbitAura } from './RabbitAura';
import { HomeHero, ProductVideo, Reveal } from './Marketing';
import { SiteHeader } from './SiteHeader';
import { NewsRibbon } from './NewsRibbon';
import { SiteFooter } from './SiteFooter';
import { ToolCatalog } from './ToolCatalog';
import { DecupagemScene, LegendasScene } from '@/components/landing/v3/scenes';
import { FAQ } from '@/lib/faq';

export function LandingV3() {
  return <main className="ae-home"><a href="#suite" className="ae-skip-link">Pular para as ferramentas</a><SiteHeader /><HomeHero />
    <NewsRibbon />
    <section className="ae-container ae-section" id="destaques"><p className="ae-section-kicker"><span aria-hidden>01</span>Em destaque</p><div className="ae-section-heading"><h2><SmokeText text="Seu próximo vídeo" /><br /><span className="ae-headline-accent"><SmokeText text="começa aqui." /></span></h2><p>Crie takes, dê ritmo à fala e prepare cada detalhe da sua próxima entrega.</p></div>
      <Reveal className="ae-feature-wide"><div className="ae-feature-copy"><span className="ae-eyebrow">FAMOUS HEY</span><h3>Uma imagem.<br />A fala que você criou.</h3><p>Transforme uma imagem em um take de avatar. Digite o texto ou adicione o áudio da sua fala.</p><p className="ae-availability">Para contas com acesso ao Famous Hey.</p><a href="#suite" className="ae-text-link">Explorar a suíte <span aria-hidden>↗</span></a></div><div className="ae-feature-media"><ProductVideo name="famous-hey" /></div></Reveal>
      <div className="ae-feature-pair"><Reveal className="ae-feature"><div className="ae-feature-scene"><LegendasScene /></div><div className="ae-feature-copy"><span className="ae-eyebrow">LEGENDAS AUTOMÁTICAS</span><h3>Texto que acompanha<br />o ritmo da sua fala.</h3><p>Escolha entre 491 modelos, ajuste no preview e exporte seu vídeo com as legendas prontas.</p><Link href="/register?next=/tools/tipografia" className="ae-text-link">Criar minhas legendas <span aria-hidden>↗</span></Link></div></Reveal><Reveal className="ae-feature"><div className="ae-feature-scene ae-cut-scene"><DecupagemScene /></div><div className="ae-feature-copy"><span className="ae-eyebrow">DECUPAGEM</span><h3>Menos silêncio.<br />Mais ritmo.</h3><p>Remova pausas, nivele o volume e processe vários arquivos na mesma fila.</p><Link href="/register?next=/tools/decupagem" className="ae-text-link">Experimentar a decupagem <span aria-hidden>↗</span></Link></div></Reveal></div>
    </section>
    <section className="ae-container ae-section ae-suite" id="suite"><p className="ae-section-kicker"><span aria-hidden>02</span>Sua suíte de edição</p><div className="ae-section-heading"><h2><SmokeText text="O que você" /><br /><span className="ae-headline-accent"><SmokeText text="vai criar hoje?" /></span></h2><p>Crie, edite ou prepare os arquivos. Escolha a etapa e encontre a ferramenta para continuar.</p></div><ToolCatalog /></section>
    <section className="ae-workflow" id="como"><div className="ae-container"><p className="ae-section-kicker"><span aria-hidden>03</span>Do início à entrega</p><div className="ae-section-heading"><h2><SmokeText text="Do arquivo bruto" /><br /><span className="ae-headline-accent"><SmokeText text="à sua próxima entrega." /></span></h2><Link href="/register" className="ae-text-link">Começar agora <span aria-hidden>↗</span></Link></div><ol className="ae-steps">{[{title:'Escolha sua ferramenta',copy:'Encontre o que precisa entre as opções de criação, edição e preparação.'},{title:'Ajuste do seu jeito',copy:'Adicione seus arquivos, configure o resultado e acompanhe o processamento.'},{title:'Revise e exporte',copy:'Confira o resultado e baixe os arquivos para continuar no seu editor.'}].map((step,i)=><li key={step.title}><span className="ae-step-number">{i+1}</span><h3>{step.title}</h3><p>{step.copy}</p></li>)}</ol></div></section>
    <section className="ae-container ae-section" id="planos"><p className="ae-section-kicker"><span aria-hidden>04</span>Escolha seu acesso</p><div className="ae-section-heading"><h2><SmokeText text="Comece grátis." /><br /><span className="ae-headline-accent"><SmokeText text="Cresça com o Premium." /></span></h2><p>Escolha o acesso que faz sentido para o seu fluxo de trabalho.</p></div><div className="ae-pricing-summary"><div><div className="ae-summary-rabbit"><RabbitAura tier={0} hue="#c084fc" glow="rgba(167,139,250,.45)" /></div><span className="ae-eyebrow">FREE</span><h3>R$ 0</h3><p>Decupagem, FakePrint, legendas, compressor, downloader e normalizador.</p><Link className="ae-button ae-button-secondary" href="/register">Criar conta grátis <span aria-hidden>↗</span></Link></div><div className="ae-premium-summary"><div className="ae-summary-rabbit"><RabbitAura tier={2} hue="#f472b6" glow="rgba(244,114,182,.55)" /></div><span className="ae-eyebrow">PREMIUM</span><h3>R$ 57 <small>/mês</small></h3><p>Todos os recursos do Free, mais Lipsync, SRT, Camuflagem, Mixer e Dividir áudios.</p><Link className="ae-button" data-ripple href="/planos">Conhecer o Premium <span aria-hidden>↗</span></Link><span className="ae-price-note">Ou R$ 540 por 12 meses de acesso, em até 12× no cartão. <strong>Sem renovação automática no anual.</strong></span></div></div></section>
    <section className="ae-container ae-section ae-faq" id="faq"><div><h2>Alguma dúvida?</h2><p>Os detalhes antes de começar.</p></div><div>{FAQ.map(item=><details key={item.q}><summary>{item.q}<span aria-hidden>+</span></summary><p>{item.a}</p></details>)}</div></section>
    <section className="ae-container ae-final-cta"><div><h2>Seu tempo é para criar.</h2><p>Deixe o repetitivo com o Auto Edit.</p></div><Link className="ae-button" data-ripple href="/register">Criar conta grátis <span aria-hidden>↗</span></Link></section><NewsRibbon variant="colophon" /><SiteFooter /></main>;
}
