/**
 * Catálogo de modelos da Tipografia Automática — 61 letterings animados
 * no espírito dos packs MOGRT de Premiere (in/out por unidade, stagger,
 * overshoot/elastic/bounce, karaokê, glitch de fatias, chroma RGB, extrude
 * 3D, sombra dura de pôster, caixas/barras inclinadas, neon).
 *
 * Cada preset é DATA — o lib/typography/engine.ts implementa as primitivas.
 * defaultPrimary/defaultAccent são o esquema de cor de fábrica; o user pode
 * sobrescrever os dois no editor sem trocar de modelo.
 */

import type { TypoPreset } from './engine';

const WHITE = '#ffffff';
const INK = '#0f0f10';
const YELLOW = '#ffd60a';
const LIME = '#c8e87c';
const CYAN = '#22d3ee';
const PINK = '#f472b6';
const RED = '#ff2d55';
const VIOLET = '#a78bfa';
const ORANGE = '#ff9f0a';
const GREEN_TERM = '#4ade80';

type P = Partial<TypoPreset> & Pick<TypoPreset, 'id' | 'name' | 'cat' | 'font' | 'in'>;

function p(base: P): TypoPreset {
  return {
    size: 0.062,
    uppercase: true,
    lineHeight: 1.16,
    fill: 'primary',
    unit: 'word',
    out: { kind: 'none', dur: 0 },
    highlightStyle: 'color',
    defaultPrimary: WHITE,
    defaultAccent: YELLOW,
    ...base,
  } as TypoPreset;
}

export const TYPO_PRESETS: TypoPreset[] = [
  // ─── IMPACTO ──────────────────────────────────────────────────────────────
  p({
    id: 'pop-punch',
    name: 'Pop Punch',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.066,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 70 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
  }),
  p({
    id: 'extrude-slam',
    name: '3D Slam',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.068,
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', stagger: 80, amp: 1.4 },
    extrude: { color: 'accent', x: 0.055, y: 0.065, steps: 6 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.1, y: 0.12 },
    blockRotate: -2,
    defaultAccent: '#b45309',
  }),
  p({
    id: 'stomp',
    name: 'Stomp',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.07,
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 90, amp: 1.4 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.09 },
    blockRotate: -1.5,
  }),
  p({
    id: 'carimbo',
    name: 'Carimbo',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 180, ease: 'outQuint', amp: 2.2 },
    stroke: { color: 'accent', width: 0.1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    blockRotateJitter: 4,
    defaultAccent: RED,
  }),
  p({
    id: 'barra-impacto',
    name: 'Barra de Impacto',
    cat: 'Impacto',
    font: 'oswald600',
    size: 0.068,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'wipe', dur: 380, ease: 'outExpo', stagger: 90 },
    bar: { color: 'accent', thickness: 0.16, skew: -10 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    defaultAccent: RED,
  }),
  p({
    id: 'zoom-crush',
    name: 'Zoom Crush',
    cat: 'Impacto',
    font: 'anton',
    size: 0.082,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 1.9 },
    out: { kind: 'zoom', dur: 140 },
    stroke: { color: INK, width: 0.12 },
    chroma: { amp: 0.022 },
  }),
  p({
    id: 'slam-giro',
    name: 'Slam Giro',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'rotate-in', dur: 320, ease: 'outBack', stagger: 80, amp: 0.9 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.07 },
  }),
  p({
    id: 'soco-alternado',
    name: 'Soco Alternado',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.068,
    in: { kind: 'squash', dur: 260, ease: 'outBack', stagger: 110 },
    stroke: { color: INK, width: 0.16 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),

  // ─── KARAOKÊ ──────────────────────────────────────────────────────────────
  p({
    id: 'karaoke-fill',
    name: 'Karaokê Fill',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.06,
    karaoke: 'fill',
    unit: 'block',
    in: { kind: 'fade', dur: 140 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: LIME,
  }),
  p({
    id: 'palavra-box',
    name: 'Palavra Box',
    cat: 'Karaokê',
    font: 'inter800',
    size: 0.056,
    karaoke: 'word-box',
    unit: 'block',
    in: { kind: 'rise', dur: 200, ease: 'outCubic', amp: 0.45 },
    box: { mode: 'none', fill: 'accent', radius: 0.18, padX: 0.22, padY: 0.14, skew: -6, shadow: { color: 'rgba(0,0,0,0.45)', x: 0.06, y: 0.08 } },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'palavra-cor',
    name: 'Palavra Cor',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.062,
    karaoke: 'word-color',
    unit: 'block',
    in: { kind: 'pop', dur: 200, ease: 'outBackSoft' },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'karaoke-zoom',
    name: 'Karaokê Zoom',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.06,
    karaoke: 'word-zoom',
    unit: 'block',
    in: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'um-por-um',
    name: 'Um Por Um',
    cat: 'Karaokê',
    font: 'anton',
    size: 0.095,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'pop', dur: 150, ease: 'outBack' },
    stroke: { color: INK, width: 0.11 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.08 },
    blockRotateJitter: 2.5,
  }),
  p({
    id: 'solo-box',
    name: 'Solo Box',
    cat: 'Karaokê',
    font: 'archivo',
    size: 0.08,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'squash', dur: 200, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.16, padX: 0.4, padY: 0.22, skew: -7, autoText: true, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.11 } },
    blockRotateJitter: 3.5,
    highlightColor: YELLOW,
    defaultAccent: RED,
  }),
  p({
    id: 'sublinha-ativa',
    name: 'Sublinha Ativa',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.058,
    karaoke: 'word-underline',
    unit: 'block',
    in: { kind: 'rise', dur: 220, ease: 'outCubic', amp: 0.5 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
    defaultAccent: LIME,
  }),

  // ─── GLITCH ───────────────────────────────────────────────────────────────
  p({
    id: 'glitch-brutal',
    name: 'Glitch Brutal',
    cat: 'Glitch',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'glitch', dur: 420, ease: 'outCubic', amp: 1.6 },
    chroma: { amp: 0.045, flicker: true },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
  }),
  p({
    id: 'glitch-rgb',
    name: 'Glitch RGB',
    cat: 'Glitch',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'glitch', dur: 420, ease: 'outQuad', stagger: 60, amp: 1.2 },
    chroma: { amp: 0.028 },
    glitchBands: true,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
  }),
  p({
    id: 'glitch-digital',
    name: 'Glitch Digital',
    cat: 'Glitch',
    font: 'anton',
    size: 0.072,
    unit: 'block',
    in: { kind: 'glitch', dur: 360, ease: 'outCubic', amp: 1.6 },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    stroke: { color: INK, width: 0.1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'vhs',
    name: 'VHS',
    cat: 'Glitch',
    font: 'inter800',
    size: 0.056,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'fade', dur: 200 },
    chroma: { amp: 0.05, flicker: true },
    loop: { kind: 'float', amp: 0.04, freq: 0.7 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0 },
  }),
  p({
    id: 'static-pop',
    name: 'Static Pop',
    cat: 'Glitch',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'pop', dur: 180, ease: 'outQuint', stagger: 60 },
    chroma: { amp: 0.03, flicker: true },
    loop: { kind: 'flicker', amp: 0.25, freq: 9 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: RED,
  }),

  // ─── DESTAQUE ─────────────────────────────────────────────────────────────
  p({
    id: 'poster-stack',
    name: 'Pôster',
    cat: 'Destaque',
    font: 'anton',
    size: 0.062,
    lineHeight: 1.02,
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    highlightScale: 1.5,
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-solida',
    name: 'Caixa Sólida',
    cat: 'Destaque',
    font: 'montserrat900',
    size: 0.058,
    unit: 'block',
    in: { kind: 'pop', dur: 260, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.2, padX: 0.5, padY: 0.3, skew: -4, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.1 } },
    fill: '#0f0f10',
    highlightColor: RED,
    defaultPrimary: INK,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-branca',
    name: 'Caixa Branca',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.054,
    unit: 'block',
    in: { kind: 'rise', dur: 260, ease: 'outBackSoft', amp: 0.5 },
    box: { mode: 'line', fill: '#ffffff', radius: 0.18, padX: 0.4, padY: 0.18, shadow: { color: 'rgba(0,0,0,0.35)', x: 0, y: 0.08 } },
    fill: '#111111',
    defaultPrimary: '#111111',
    defaultAccent: RED,
  }),
  p({
    id: 'empilhado',
    name: 'Empilhado',
    cat: 'Destaque',
    font: 'archivo',
    size: 0.054,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 100 },
    box: { mode: 'word', fill: '#111111', radius: 0.1, padX: 0.26, padY: 0.18, skew: -5, autoText: true, cycle: ['accent', '#141414', '#ffffff'], shadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.08 } },
    wordRotateJitter: 2.5,
    defaultAccent: RED,
  }),
  p({
    id: 'adesivo',
    name: 'Adesivo',
    cat: 'Destaque',
    font: 'nunito900',
    size: 0.062,
    in: { kind: 'pop', dur: 480, ease: 'elastic', stagger: 100 },
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.26 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.09 },
    wordRotateJitter: 3,
    highlightColor: YELLOW,
    defaultAccent: PINK,
  }),
  p({
    id: 'tarja-preta',
    name: 'Tarja Preta',
    cat: 'Destaque',
    font: 'oswald600',
    size: 0.06,
    unit: 'block',
    in: { kind: 'wipe', dur: 360, ease: 'outExpo', stagger: 80 },
    box: { mode: 'line', fill: 'rgba(0,0,0,0.85)', radius: 0.04, padX: 0.4, padY: 0.14, skew: -4 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chip-palavra',
    name: 'Chip Palavra',
    cat: 'Destaque',
    font: 'poppins800',
    size: 0.05,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 90 },
    box: { mode: 'word', fill: 'rgba(0,0,0,0.8)', radius: 0.3, padX: 0.3, padY: 0.2 },
    defaultAccent: LIME,
    highlightStyle: 'box',
  }),
  p({
    id: 'marca-texto',
    name: 'Marca-Texto',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 280, ease: 'outCubic', stagger: 70, amp: 0.4 },
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'sublinhado-forte',
    name: 'Sublinhado',
    cat: 'Destaque',
    font: 'montserrat800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'fade', dur: 260, ease: 'outQuad', stagger: 60 },
    highlightStyle: 'underline',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: LIME,
  }),

  // ─── MINIMAL ──────────────────────────────────────────────────────────────
  p({
    id: 'fade-limpo',
    name: 'Fade Limpo',
    cat: 'Minimal',
    font: 'inter800',
    size: 0.052,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 320, ease: 'outQuad' },
    out: { kind: 'fade', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'sobe-suave',
    name: 'Sobe Suave',
    cat: 'Minimal',
    font: 'poppins800',
    size: 0.054,
    uppercase: false,
    in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 60, amp: 0.7 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'tracking-aberto',
    name: 'Tracking Aberto',
    cat: 'Minimal',
    font: 'montserrat800',
    size: 0.05,
    spacing: 0.06,
    unit: 'block',
    in: { kind: 'tracking-in', dur: 420, ease: 'outExpo', amp: 0.7 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'oswald-clean',
    name: 'Alto e Limpo',
    cat: 'Minimal',
    font: 'oswald600',
    size: 0.062,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'blur', dur: 300, ease: 'outCubic', amp: 0.8 },
    out: { kind: 'blur', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.14, x: 0, y: 0.05 },
  }),

  // ─── BOUNCE ───────────────────────────────────────────────────────────────
  p({
    id: 'bounce-elastico',
    name: 'Bounce Elástico',
    cat: 'Bounce',
    font: 'poppins800',
    size: 0.062,
    in: { kind: 'pop', dur: 560, ease: 'elastic', stagger: 90 },
    stroke: { color: INK, width: 0.13 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: PINK,
  }),
  p({
    id: 'jelly',
    name: 'Jelly',
    cat: 'Bounce',
    font: 'nunito900',
    size: 0.064,
    in: { kind: 'squash', dur: 420, ease: 'elastic', stagger: 100 },
    stroke: { color: INK, width: 0.15 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'quica-letra',
    name: 'Quica Letra',
    cat: 'Bounce',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'drop', dur: 340, ease: 'bounce', stagger: 26, amp: 1.1 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
  }),

  // ─── MÁQUINA ──────────────────────────────────────────────────────────────
  p({
    id: 'maquina',
    name: 'Máquina',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.05,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 900 },
    caret: 'bar',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: WHITE,
  }),
  p({
    id: 'terminal',
    name: 'Terminal',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.048,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 800 },
    caret: 'block',
    fill: '#4ade80',
    glow: { color: GREEN_TERM, blur: 0.5 },
    defaultPrimary: GREEN_TERM,
    defaultAccent: GREEN_TERM,
  }),
  p({
    id: 'digitada',
    name: 'Digitada',
    cat: 'Máquina',
    font: 'inter800',
    size: 0.054,
    uppercase: true,
    unit: 'block',
    in: { kind: 'typewriter', dur: 620 },
    caret: 'bar',
    box: { mode: 'line', fill: 'rgba(0,0,0,0.72)', radius: 0.16, padX: 0.34, padY: 0.16 },
    defaultAccent: ORANGE,
  }),

  // ─── FOCO ─────────────────────────────────────────────────────────────────
  p({
    id: 'blur-reveal',
    name: 'Blur Reveal',
    cat: 'Foco',
    font: 'poppins800',
    size: 0.058,
    in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 80, amp: 1 },
    out: { kind: 'blur', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'foco-cine',
    name: 'Foco Cine',
    cat: 'Foco',
    font: 'playfair900',
    size: 0.06,
    uppercase: false,
    unit: 'block',
    in: { kind: 'blur-zoom', dur: 520, ease: 'outQuint', amp: 1 },
    out: { kind: 'blur', dur: 260 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
  }),
  p({
    id: 'motion-slide',
    name: 'Motion Slide',
    cat: 'Foco',
    font: 'inter800',
    size: 0.056,
    in: { kind: 'slide-left', dur: 300, ease: 'outExpo', stagger: 55, amp: 1 },
    out: { kind: 'fade', dur: 150 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),

  // ─── REVEAL ───────────────────────────────────────────────────────────────
  p({
    id: 'mask-up',
    name: 'Mask Up',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.06,
    unit: 'block',
    in: { kind: 'mask-up', dur: 380, ease: 'outQuint', stagger: 110 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'cortina',
    name: 'Cortina',
    cat: 'Reveal',
    font: 'anton',
    size: 0.07,
    unit: 'block',
    in: { kind: 'wipe', dur: 420, ease: 'outExpo', stagger: 90 },
    out: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.1 },
  }),
  p({
    id: 'flip-belt',
    name: 'Flip 3D',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'flip', dur: 340, ease: 'outBack', stagger: 90 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: ORANGE,
  }),
  p({
    id: 'stretch-impact',
    name: 'Stretch',
    cat: 'Reveal',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'stretch-x', dur: 320, ease: 'outBack', amp: 1.6 },
    stroke: { color: INK, width: 0.11 },
  }),
  p({
    id: 'skew-kinetic',
    name: 'Skew Kinetic',
    cat: 'Reveal',
    font: 'poppins800',
    size: 0.06,
    in: { kind: 'skew-slide', dur: 300, ease: 'outExpo', stagger: 70 },
    out: { kind: 'fade', dur: 140 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0.03, y: 0.05 },
  }),

  // ─── NEON ─────────────────────────────────────────────────────────────────
  p({
    id: 'neon-brutal',
    name: 'Neon Brutal',
    cat: 'Neon',
    font: 'bebas',
    size: 0.086,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 240, ease: 'outQuint', amp: 0.9 },
    glow: { color: 'accent', blur: 0.65 },
    stroke: { color: '#ffffff', width: 0.045 },
    chroma: { amp: 0.02, flicker: true },
    loop: { kind: 'flicker', amp: 0.5, freq: 12 },
    defaultAccent: PINK,
  }),
  p({
    id: 'neon-pulse',
    name: 'Neon Pulse',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'fade', dur: 260, ease: 'outQuad' },
    loop: { kind: 'flicker', amp: 0.55, freq: 11 },
    glow: { color: 'accent', blur: 0.55 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'neon-rosa',
    name: 'Neon Rosa',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    in: { kind: 'pop', dur: 260, ease: 'outBackSoft', stagger: 80 },
    glow: { color: 'accent', blur: 0.5 },
    loop: { kind: 'pulse', amp: 0.05, freq: 1.6 },
    defaultAccent: PINK,
  }),
  p({
    id: 'luz-de-palco',
    name: 'Luz de Palco',
    cat: 'Neon',
    font: 'anton',
    size: 0.08,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    glow: { color: 'accent', blur: 0.7 },
    loop: { kind: 'pulse', amp: 0.04, freq: 1.1 },
    defaultAccent: YELLOW,
  }),

  // ─── KINETIC ──────────────────────────────────────────────────────────────
  p({
    id: 'duas-cores',
    name: 'Duas Cores',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'skew-slide', dur: 280, ease: 'outExpo', stagger: 80 },
    colorCycle: ['primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.045, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chroma-wave',
    name: 'Chroma Wave',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    chroma: { amp: 0.035 },
    loop: { kind: 'wave', amp: 0.07, freq: 1.4 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'onda',
    name: 'Onda',
    cat: 'Kinetic',
    font: 'nunito900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    loop: { kind: 'wave', amp: 0.09, freq: 1.6 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'shake-hype',
    name: 'Shake Hype',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 220, ease: 'outQuint', amp: 1 },
    loop: { kind: 'shake', amp: 0.05, freq: 8 },
    stroke: { color: INK, width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),
  p({
    id: 'float-suave',
    name: 'Float Suave',
    cat: 'Kinetic',
    font: 'poppins800',
    size: 0.056,
    uppercase: false,
    unit: 'block',
    in: { kind: 'rise', dur: 380, ease: 'outQuint', amp: 0.6 },
    loop: { kind: 'float', amp: 0.05, freq: 0.9 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'letra-viva',
    name: 'Letra Viva',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 22 },
    loop: { kind: 'wave', amp: 0.05, freq: 1.2 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: LIME,
  }),

  // ─── EDITORIAL ────────────────────────────────────────────────────────────
  p({
    id: 'editorial-destaque',
    name: 'Editorial Destaque',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'mask-up', dur: 420, ease: 'outQuint', stagger: 120 },
    highlightScale: 1.32,
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'editorial-serif',
    name: 'Editorial',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 420, ease: 'outQuad' },
    out: { kind: 'fade', dur: 240 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'vogue-mask',
    name: 'Vogue',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.06,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'mask-up', dur: 460, ease: 'outQuint', stagger: 130 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.03 },
  }),
  p({
    id: 'citacao',
    name: 'Citação',
    cat: 'Editorial',
    font: 'playfair900i',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 380, ease: 'outQuint', stagger: 80, amp: 0.5 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'rabisco',
    name: 'Rabisco',
    cat: 'Editorial',
    font: 'marker',
    size: 0.06,
    uppercase: false,
    in: { kind: 'rotate-in', dur: 300, ease: 'outBack', stagger: 100, amp: 0.5 },
    wordRotateJitter: 2,
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    defaultAccent: YELLOW,
  }),
];

export const TYPO_CATEGORIES: string[] = Array.from(
  new Set(TYPO_PRESETS.map((pr) => pr.cat)),
);

export function getPreset(id: string): TypoPreset {
  return TYPO_PRESETS.find((pr) => pr.id === id) ?? TYPO_PRESETS[0];
}
