/**
 * Catálogo de modelos da Tipografia Automática — 80 letterings animados
 * no espírito dos packs MOGRT de Premiere (in/out por unidade, stagger,
 * overshoot/elastic/bounce, karaokê, glitch de fatias, chroma RGB, extrude
 * 3D, sombra dura de pôster, caixas/barras inclinadas, neon, ouro/chrome
 * com shine sweep, duotone, aura, tamanhos alternados e DESTAQUE AUTOMÁTICO
 * da palavra forte de cada bloco).
 *
 * Cada preset é DATA — o lib/typography/engine.ts implementa as primitivas.
 * defaultPrimary/defaultAccent são o esquema de cor de fábrica; o user pode
 * sobrescrever os dois no editor sem trocar de modelo.
 */

import type { TypoPreset } from './engine';
import { GENERATED_PRESETS } from './presets-gen';

const WHITE = '#ffffff';
const INK = '#0f0f10';
const YELLOW = '#ffd60a';
const LIME = '#c8e87c';
const CYAN = '#22d3ee';
const PINK = '#f472b6';
const RED = '#ff2d55';
const VIOLET = '#a78bfa';
const ORANGE = '#ff9f0a';
const GREEN_TERM = '#4ade80';

type P = Partial<TypoPreset> & Pick<TypoPreset, 'id' | 'name' | 'cat' | 'font' | 'in'>;

function p(base: P): TypoPreset {
  return {
    size: 0.062,
    uppercase: true,
    lineHeight: 1.16,
    fill: 'primary',
    unit: 'word',
    out: { kind: 'none', dur: 0 },
    highlightStyle: 'color',
    defaultPrimary: WHITE,
    defaultAccent: YELLOW,
    ...base,
  } as TypoPreset;
}

const MANUAL_PRESETS: TypoPreset[] = [
  // ─── VIRAL (tipografia mista, refs validadas pelo user) ──────────────────
  p({
    id: 'titulo-viral',
    emphasisBreak: true,
    name: 'Título Viral',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.045 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.045, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.44, lowercase: true },
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.6 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'titulo-ouro',
    emphasisBreak: true,
    name: 'Título Ouro',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3c4'],
      [0.4, '#ffcd3c'],
      [0.62, '#c98a12'],
      [0.75, '#f2b02c'],
      [1, '#8f5e00'],
    ],
    shine: { period: 2600, alpha: 0.75 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.42, lowercase: true },
    in: { kind: 'rise', dur: 320, ease: 'outQuint', stagger: 100, amp: 0.6 },
    autoEmphasis: true,
    defaultAccent: '#ffcd3c',
  }),
  p({
    id: 'viral-clean',
    emphasisBreak: true,
    name: 'Essa Forma',
    cat: 'Viral',
    font: 'archivo',
    size: 0.074,
    lineHeight: 1.02,
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.04, y: 0.05 },
    mix: { font: 'caveat700', scale: 0.72, lowercase: true, accentLast: true },
    in: { kind: 'pop', dur: 280, ease: 'outBackSoft', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: ORANGE,
  }),
  p({
    id: 'neon-viral',
    emphasisBreak: true,
    name: 'Neon Viral',
    cat: 'Viral',
    font: 'bebas',
    size: 0.086,
    lineHeight: 1.0,
    spacing: 0.02,
    glow: { color: 'accent', blur: 0.42 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.04 },
    mix: { font: 'playfair900i', scale: 0.42, lowercase: true },
    in: { kind: 'fade', dur: 260, ease: 'outQuad', stagger: 90 },
    autoEmphasis: true,
    defaultAccent: PINK,
  }),
  p({
    id: 'contraste',
    emphasisBreak: true,
    name: 'Contraste',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.07,
    lineHeight: 1.04,
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.52, lowercase: true, color: 'accent' },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 90 },
    autoEmphasis: true,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'revista',
    emphasisBreak: true,
    name: 'Revista',
    cat: 'Viral',
    font: 'playfair900',
    size: 0.072,
    lineHeight: 1.04,
    uppercase: false,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    mix: { font: 'oswald600', scale: 0.46 },
    in: { kind: 'mask-up', dur: 400, ease: 'outQuint', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'linha-destaque',
    name: 'Linha Rosa',
    cat: 'Viral',
    font: 'oswald600',
    size: 0.064,
    lineHeight: 1.12,
    lineAccent: 'last',
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.03, y: 0.04 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 110 },
    autoEmphasis: false,
    defaultAccent: PINK,
  }),
  p({
    id: 'manuscrito',
    name: 'Manuscrito',
    cat: 'Viral',
    font: 'caveat700',
    size: 0.078,
    uppercase: false,
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.05 },
    in: { kind: 'rise', dur: 340, ease: 'outBackSoft', stagger: 100, amp: 0.5 },
    autoEmphasis: true,
    highlightScale: 1.25,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'escada',
    name: 'Escada',
    cat: 'Viral',
    font: 'anton',
    size: 0.06,
    lineHeight: 1.05,
    sizeCycle: [0.78, 1.02, 1.34],
    colorCycle: ['primary', 'primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'esmagado',
    name: 'Esmagado',
    cat: 'Viral',
    font: 'archivo',
    size: 0.06,
    lineHeight: 1.04,
    sizeCycle: [1.42, 0.74],
    colorCycle: ['accent', 'primary'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'squash', dur: 280, ease: 'outBack', stagger: 100 },
    defaultAccent: ORANGE,
  }),
  // ⭐ Referencia do Silas (01.09): fala em MINUSCULAS, branca com palavras
  // em dourado, sombra macia por baixo, e a entrada palavra a palavra em que
  // cada uma nasce MAIOR e translucida e assenta no tamanho (zoom-out) — e o
  // que se ve no frame do meio da animacao que ele mandou.
  p({
    id: 'papo-amarelo',
    name: 'Papo Amarelo',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.062,
    lineHeight: 1.1,
    uppercase: false,
    spacing: -0.012,
    fill: 'primary',
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.1, x: 0, y: 0.035 },
    unit: 'word',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', stagger: 90, amp: 0.5 },
    autoEmphasis: true,
    highlightStyle: 'color',
    // O amarelo da referencia nao e chapado: tem um brilho de leve, como
    // metal. Sai de um gradiente vertical claro->ouro->ambar dentro da
    // propria letra, mais um glow curto na cor de destaque.
    highlightGradient: [
      [0, '#fff6c9'],
      [0.34, '#ffd84a'],
      [0.62, '#f0b21c'],
      [1, '#e39a10'],
    ],
    defaultPrimary: '#ffffff',
    defaultAccent: '#f5c518',
  }),
  p({
    id: 'letterings-amarelo',
    emphasisBreak: true,
    name: 'Letterings',
    cat: 'Viral',
    font: 'lilita',
    size: 0.078,
    lineHeight: 1.0,
    uppercase: false,
    fill: 'accent',
    stroke: { color: '#161616', width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.05, y: 0.07 },
    mix: { font: 'playfair900i', scale: 0.46, lowercase: true },
    in: { kind: 'pop', dur: 340, ease: 'outBackSoft', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'presets-3d',
    name: '3D Dinâmico',
    cat: 'Viral',
    font: 'archivo',
    size: 0.072,
    lineHeight: 0.98,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.45, '#dde3ea'],
      [0.55, '#9aa5b1'],
      [1, '#cfd6de'],
    ],
    extrude: { color: '#3b3644', x: 0.055, y: 0.06, steps: 7 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.09, y: 0.1 },
    glow: { color: 'accent', blur: 0.18 },
    emphasisBreak: true,
    highlightGradient: [
      [0, '#e7d9ff'],
      [0.42, '#b18cff'],
      [0.6, '#6b3fd4'],
      [1, '#9d78ea'],
    ],
    highlightScale: 1.22,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 1.1 },
    autoEmphasis: true,
    defaultAccent: '#b18cff',
  }),
  p({
    id: 'verde-dinheiro',
    emphasisBreak: true,
    name: 'Verde Dinheiro',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: '#2eff4f',
    extrude: { color: '#0b6b1d', x: 0.05, y: 0.06, steps: 6 },
    stroke: { color: '#052e0d', width: 0.06 },
    glow: { color: '#2eff4f', blur: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    highlightScale: 1.24,
    mix: { font: 'oswald600', scale: 0.42 },
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 100, amp: 1.1 },
    autoEmphasis: true,
    defaultPrimary: WHITE,
    defaultAccent: '#2eff4f',
  }),
  p({
    id: 'recursos-gold',
    emphasisBreak: true,
    name: 'Mais de 5000',
    cat: 'Viral',
    font: 'passion700',
    size: 0.082,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9a8'],
      [0.45, '#ffb52e'],
      [0.65, '#c46a00'],
      [1, '#ff9412'],
    ],
    shine: { period: 2400, alpha: 0.7 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    mix: { font: 'caveat700', scale: 0.62, lowercase: true, dy: 0.18 },
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', stagger: 90, amp: 1 },
    autoEmphasis: true,
    defaultAccent: '#ffb52e',
  }),
  p({
    id: 'edicao-3d',
    name: 'Edição 3D',
    cat: 'Viral',
    font: 'archivo',
    size: 0.072,
    lineHeight: 0.98,
    uppercase: false,
    stack: true,
    extrude: { color: '#8a8f98', x: 0.06, y: 0.065, steps: 7 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.1, y: 0.11 },
    highlightGradient: [
      [0, '#ffe9a8'],
      [0.42, '#f5b93d'],
      [0.6, '#a06b00'],
      [1, '#e2a52e'],
    ],
    highlightScale: 1.18,
    in: { kind: 'drop', dur: 320, ease: 'outBack', stagger: 100, amp: 1 },
    autoEmphasis: true,
    defaultAccent: '#f0b429',
  }),
  p({
    id: 'comenta-pack',
    stack: true,
    name: 'Comenta Pack',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.06,
    lineHeight: 1.08,
    uppercase: false,
    glow: { color: '#ffffff', blur: 0.2 },
    in: { kind: 'fade', dur: 220, ease: 'outQuad', stagger: 80 },
    autoEmphasis: true,
    highlightColor: RED,
    defaultAccent: RED,
  }),
  p({
    id: 'minutos',
    emphasisBreak: true,
    name: 'Minutos',
    cat: 'Viral',
    font: 'playfair900i',
    size: 0.08,
    lineHeight: 1.0,
    uppercase: false,
    frameLines: { color: 'primary', thickness: 0.035, gap: 0.5 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    mix: { font: 'oswald600', scale: 0.38 },
    in: { kind: 'mask-up', dur: 380, ease: 'outQuint', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: WHITE,
  }),
  p({
    id: 'cartaz-3d',
    name: 'Cartaz 3D',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.068,
    lineHeight: 1.03,
    extrude: { color: '#26262c', x: 0.05, y: 0.06, steps: 8 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.11 },
    lineAccent: 'last',
    unit: 'block',
    in: { kind: 'zoom-out', dur: 280, ease: 'outQuint', amp: 1.3 },
    autoEmphasis: false,
    defaultAccent: RED,
  }),
  p({
    id: 'um-click',
    name: '1 Click',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.072,
    lineHeight: 1.0,
    stroke: { color: INK, width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.04, y: 0.06 },
    mix: { font: 'caveat700', scale: 0.66, lowercase: true, color: 'accent', dy: 0.22 },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: ORANGE,
  }),
  p({
    id: 'eco-azul',
    name: 'Reflexo Script',
    cat: 'Viral',
    font: 'playfair900i',
    size: 0.068,
    uppercase: false,
    echoes: [{ pos: 'below', scale: 0.9, gap: 0.06, color: 'accent', alpha: 0.24, flipY: true, glow: 0.4 }],
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    unit: 'block',
    in: { kind: 'blur', dur: 360, ease: 'outCubic', amp: 0.9 },
    autoEmphasis: false,
    defaultAccent: CYAN,
  }),
  p({
    id: 'aesthetic-3d',
    stack: true,
    name: 'Aesthetic 3D',
    cat: 'Viral',
    font: 'bowlbysc',
    size: 0.07,
    lineHeight: 1.02,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff2c8'],
      [0.45, '#f2c14e'],
      [0.62, '#a06b00'],
      [1, '#e0a828'],
    ],
    extrude: { color: '#5c4200', x: 0.05, y: 0.06, steps: 6 },
    glow: { color: '#ffd970', blur: 0.28 },
    shine: { period: 2200, alpha: 0.7 },
    wordRotateJitter: 1.5,
    in: { kind: 'drop', dur: 320, ease: 'bounce', stagger: 110, amp: 1 },
    autoEmphasis: false,
    defaultAccent: '#f2c14e',
  }),
  p({
    id: 'risco-vermelho',
    name: 'Risco Vermelho',
    cat: 'Viral',
    font: 'inter800',
    size: 0.06,
    uppercase: false,
    swoosh: { color: 'accent', width: 0.09 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    unit: 'block',
    in: { kind: 'rise', dur: 320, ease: 'outQuint', amp: 0.5 },
    autoEmphasis: false,
    defaultAccent: '#ff2d2d',
  }),
  p({
    id: 'trippy',
    name: 'Trippy',
    cat: 'Viral',
    font: 'titan',
    size: 0.072,
    patternFill: { colors: ['#ffd60a', '#12b886'], scale: 1.1, speed: 1.2 },
    stroke: { color: '#123524', width: 0.1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'squash', dur: 300, ease: 'outBack', stagger: 100 },
    autoEmphasis: false,
    defaultAccent: '#12b886',
  }),
  p({
    id: 'fumaca',
    emphasisBreak: true,
    name: 'Fumaça',
    cat: 'Viral',
    font: 'anton',
    size: 0.078,
    smoke: { alpha: 0.5 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.04, y: 0.06 },
    loop: { kind: 'float', amp: 0.035, freq: 0.7 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 380, ease: 'outQuint', amp: 0.7 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'verde-neon',
    name: 'Verde Neon',
    cat: 'Viral',
    font: 'anton',
    size: 0.076,
    fill: '#2eff4f',
    glow: { color: '#2eff4f', blur: 0.32 },
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 90 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    highlightScale: 1.28,
    defaultPrimary: '#2eff4f',
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'script-rosa',
    emphasisBreak: true,
    name: 'Copiar Colar',
    cat: 'Viral',
    font: 'playfair900i',
    size: 0.08,
    lineHeight: 1.0,
    uppercase: false,
    fill: '#ffb59e',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    mix: { font: 'inter800', scale: 0.36 },
    in: { kind: 'rise', dur: 320, ease: 'outQuint', stagger: 100, amp: 0.5 },
    autoEmphasis: true,
    defaultPrimary: WHITE,
    defaultAccent: '#ffb59e',
  }),
  p({
    id: 'mascara',
    name: 'Máscara',
    cat: 'Viral',
    font: 'anton',
    size: 0.082,
    knockout: { dim: 0.55, pad: 0.55 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 340, ease: 'outQuint', amp: 0.6 },
    autoEmphasis: false,
    defaultAccent: WHITE,
  }),
  p({
    id: 'tricolor',
    name: 'Tricolor',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.064,
    lineHeight: 1.06,
    colorCycle: [WHITE, YELLOW, CYAN],
    stroke: { color: INK, width: 0.13 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 90 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'cromo-vermelho',
    name: 'Cromo Vermelho',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.068,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.45, '#dde3ea'],
      [0.55, '#9aa5b1'],
      [1, '#cfd6de'],
    ],
    extrude: { color: '#2a2a30', x: 0.05, y: 0.06, steps: 7 },
    emphasisBreak: true,
    highlightGradient: [
      [0, '#ffb3ba'],
      [0.42, '#ff2d55'],
      [0.62, '#a30f2d'],
      [1, '#e0244a'],
    ],
    highlightScale: 1.22,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 280, ease: 'outQuint', amp: 1.2 },
    autoEmphasis: true,
    defaultAccent: RED,
  }),
  p({
    id: 'ouro-fumaca',
    name: 'Ouro Fumaça',
    cat: 'Viral',
    font: 'anton',
    size: 0.078,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3c4'],
      [0.42, '#ffcd3c'],
      [0.62, '#a06b00'],
      [1, '#e2a52e'],
    ],
    shine: { period: 2600, alpha: 0.7 },
    smoke: { alpha: 0.42 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
    emphasisBreak: true,
    highlightScale: 1.18,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 360, ease: 'outQuint', amp: 0.8 },
    autoEmphasis: true,
    defaultAccent: '#ffcd3c',
  }),
  p({
    id: 'fogo-viral',
    name: 'Fogo Viral',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    glow: { color: '#ff7b00', blur: 0.24 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.06 },
    emphasisBreak: true,
    highlightGradient: [
      [0, '#fff3b0'],
      [0.4, '#ffb703'],
      [0.75, '#fb5607'],
      [1, '#d00000'],
    ],
    highlightScale: 1.26,
    mix: { font: 'oswald600', scale: 0.44 },
    in: { kind: 'squash', dur: 280, ease: 'outBack', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: '#ffb703',
  }),
  p({
    id: 'azul-eletrico',
    name: 'Azul Elétrico',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: '#31c4ff',
    extrude: { color: '#0a4a73', x: 0.05, y: 0.06, steps: 6 },
    stroke: { color: '#062b44', width: 0.06 },
    glow: { color: '#31c4ff', blur: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    emphasisBreak: true,
    highlightScale: 1.24,
    mix: { font: 'oswald600', scale: 0.42 },
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 100, amp: 1.1 },
    autoEmphasis: true,
    defaultPrimary: WHITE,
    defaultAccent: '#31c4ff',
  }),
  p({
    id: 'torre-3d',
    name: 'Torre 3D',
    cat: 'Viral',
    font: 'archivo',
    size: 0.066,
    lineHeight: 1.0,
    stack: true,
    colorCycle: ['primary', 'accent'],
    extrude: { color: '#26262c', x: 0.05, y: 0.055, steps: 7 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.08, y: 0.09 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 1.1 },
    autoEmphasis: false,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'glitch-viral',
    name: 'Glitch Viral',
    cat: 'Viral',
    font: 'anton',
    size: 0.078,
    lineHeight: 1.0,
    chroma: { amp: 0.04, flicker: true },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    emphasisBreak: true,
    highlightScale: 1.24,
    mix: { font: 'playfair900i', scale: 0.44, lowercase: true },
    in: { kind: 'glitch', dur: 400, ease: 'outCubic', amp: 1.4 },
    autoEmphasis: true,
    defaultAccent: CYAN,
  }),
  p({
    id: 'piramide-neon',
    name: 'Pirâmide Neon',
    cat: 'Viral',
    font: 'bebas',
    size: 0.07,
    lineHeight: 0.98,
    spacing: 0.02,
    stack: true,
    glow: { color: 'accent', blur: 0.34 },
    in: { kind: 'fade', dur: 240, ease: 'outQuad', stagger: 110 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    highlightScale: 1.22,
    defaultAccent: PINK,
  }),
  p({
    id: 'ouro-puro',
    name: 'Ouro Puro',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.07,
    lineHeight: 1.0,
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    emphasisBreak: true,
    highlightGradient: [
      [0, '#fff8dc'],
      [0.35, '#ffe08a'],
      [0.55, '#f0b429'],
      [0.68, '#8a5a00'],
      [1, '#e8a824'],
    ],
    highlightScale: 1.3,
    mix: { font: 'oswald600', scale: 0.45 },
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: '#f0b429',
  }),

  // ─── FIDELIDADE às 20 refs novas do user (rodada 8) ──────────────────────
  p({
    id: 'branco-magenta',
    name: 'Branco Magenta',
    cat: 'Viral',
    font: 'archivo',
    size: 0.076,
    lineHeight: 1.0,
    fill: '#ffffff',
    chroma: { amp: 0.042, colors: ['#ff2dc4', '#d94fff'] },
    extrude: { color: '#c9c9d4', x: 0.04, y: 0.05, steps: 4 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.9 },
    autoEmphasis: false,
    defaultAccent: '#ff2dc4',
  }),
  p({
    id: 'caixa-vermelha-ouro',
    name: 'Caixa Vermelha Ouro',
    cat: 'Viral',
    font: 'cinzel800',
    size: 0.06,
    spacing: 0.04,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9c4'],
      [0.5, '#e8b04c'],
      [1, '#a8781e'],
    ],
    box: {
      mode: 'block',
      fill: '#d92626',
      radius: 0.12,
      padX: 0.55,
      padY: 0.3,
      shadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.09 },
    },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    autoEmphasis: false,
    defaultAccent: '#e8b04c',
  }),
  p({
    id: 'roxo-reflexo',
    name: 'Roxo Reflexo',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.072,
    fill: 'gradient',
    gradientStops: [
      [0, '#d9b3ff'],
      [0.52, '#b06dff'],
      [0.58, '#5a2a99'],
      [1, '#8a4fe0'],
    ],
    glow: { color: '#a05ae0', blur: 0.2 },
    unit: 'block',
    in: { kind: 'rise', dur: 320, ease: 'outQuint', amp: 0.5 },
    autoEmphasis: false,
    defaultAccent: '#b06dff',
  }),
  p({
    id: 'eco-azul-duplo',
    name: 'Fantasma Azul',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.078,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#9beaff'],
      [0.5, '#3ab7ff'],
      [1, '#0a5bd0'],
    ],
    glow: { color: '#3ab7ff', blur: 0.28 },
    echoes: [{ pos: 'behind', scale: 1.45, color: '#3ab7ff', outline: true, alpha: 0.5 }],
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    autoEmphasis: false,
    defaultAccent: '#3ab7ff',
  }),
  p({
    id: 'eco-laranja-duplo',
    name: 'Eco Contorno',
    cat: 'Viral',
    font: 'poppins800',
    size: 0.078,
    lineHeight: 1.0,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9a8'],
      [0.5, '#ffb52e'],
      [1, '#e07800'],
    ],
    glow: { color: '#ff9f0a', blur: 0.22 },
    echoes: [
      { pos: 'behind', scale: 1.3, color: '#ffb52e', outline: true, alpha: 0.5 },
      { pos: 'behind', scale: 1.62, color: '#ffb52e', outline: true, alpha: 0.24 },
    ],
    unit: 'block',
    in: { kind: 'rise', dur: 320, ease: 'outQuint', amp: 0.5 },
    autoEmphasis: false,
    defaultAccent: '#ffb52e',
  }),
  p({
    id: 'eco-triplo-riscado',
    name: 'Trio Fantasma',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.08,
    lineHeight: 1.0,
    uppercase: false,
    fill: '#e8192c',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    echoes: [
      { pos: 'behind', scale: 1.5, color: '#ffffff', outline: true, alpha: 0.35 },
      { pos: 'below', scale: 0.88, gap: 0.08, color: '#e8192c', alpha: 0.22, flipY: true },
    ],
    unit: 'block',
    in: { kind: 'zoom-out', dur: 280, ease: 'outQuint', amp: 0.9 },
    autoEmphasis: false,
    defaultPrimary: '#e8192c',
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'fantasma-ouro',
    name: 'Fantasma Ouro',
    cat: 'Viral',
    font: 'passion700',
    size: 0.08,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3c4'],
      [0.45, '#ffcd3c'],
      [0.65, '#c98a12'],
      [1, '#f2b02c'],
    ],
    shine: { period: 2600, alpha: 0.7 },
    echoes: [{ pos: 'behind', scale: 1.55, color: '#8a6a1a', outline: true, alpha: 0.55 }],
    unit: 'block',
    in: { kind: 'zoom-out', dur: 340, ease: 'outQuint', amp: 0.7 },
    autoEmphasis: false,
    defaultAccent: '#ffcd3c',
  }),
  p({
    id: 'eco-espelho',
    name: 'Eco Espelho',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.076,
    fill: 'gradient',
    gradientStops: [
      [0, '#eafffb'],
      [0.55, '#9ff5e0'],
      [1, '#3ecfb0'],
    ],
    glow: { color: '#7fe8d0', blur: 0.2 },
    echoes: [{ pos: 'below', scale: 0.94, color: '#9ff5e0', gap: 0.05, alpha: 0.26, flipY: true, glow: 0.3 }],
    unit: 'block',
    in: { kind: 'blur', dur: 360, ease: 'outCubic', amp: 0.8 },
    autoEmphasis: false,
    defaultAccent: '#9ff5e0',
  }),
  p({
    id: 'rosa-fofa',
    name: 'Rosa Fofa',
    cat: 'Viral',
    font: 'leckerli',
    size: 0.08,
    uppercase: false,
    fill: 'accent',
    hardShadow: { color: 'rgba(120,20,90,0.5)', x: 0.04, y: 0.06 },
    unit: 'block',
    in: { kind: 'pop', dur: 420, ease: 'elastic' },
    autoEmphasis: false,
    defaultAccent: '#e858d8',
  }),
  p({
    id: 'diagonal-neon',
    name: 'Diagonal Neon',
    cat: 'Viral',
    font: 'anton',
    size: 0.088,
    lineHeight: 0.94,
    fill: 'gradient',
    gradientDir: 'diagonal',
    gradientStops: [
      [0, '#4f7dff'],
      [0.5, '#a05ae0'],
      [1, '#ff5db1'],
    ],
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 360, ease: 'outQuint', stagger: 100 },
    autoEmphasis: false,
    defaultAccent: '#a05ae0',
  }),
  p({
    id: 'encaixado-azul',
    name: 'Encaixado Azul',
    cat: 'Viral',
    font: 'dmsans900',
    size: 0.08,
    lineHeight: 0.84,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#bfe9ff'],
      [0.5, '#57b6ff'],
      [1, '#1a6ad0'],
    ],
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.14, x: 0, y: 0.05 },
    mix: { font: 'inter800', scale: 0.34 },
    emphasisBreak: true,
    autoEmphasis: true,
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.5 },
    defaultAccent: '#57b6ff',
  }),
  p({
    id: 'fatiado-ouro',
    name: 'Fatiado Ouro',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.076,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9a8'],
      [0.5, '#ffb52e'],
      [1, '#c96a00'],
    ],
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    unit: 'block',
    in: { kind: 'glitch', dur: 360, ease: 'outCubic', amp: 1.2 },
    autoEmphasis: false,
    defaultAccent: '#ffb52e',
  }),
  p({
    id: 'circulado',
    name: 'Circulado',
    cat: 'Viral',
    font: 'oswald600',
    size: 0.062,
    spacing: 0.04,
    fill: '#ffe9b0',
    circle: { color: 'accent', width: 0.07 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.03, y: 0.04 },
    unit: 'block',
    in: { kind: 'fade', dur: 260, ease: 'outQuad' },
    autoEmphasis: false,
    defaultPrimary: '#ffe9b0',
    defaultAccent: '#ffb52e',
  }),
  p({
    id: 'postit',
    name: 'Post-it',
    cat: 'Viral',
    font: 'anton',
    size: 0.076,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9c4'],
      [0.5, '#e8b04c'],
      [1, '#a06b1a'],
    ],
    sticky: { color: '#f8ee1c', rotate: -5 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.05 },
    mix: { font: 'playfair900i', scale: 0.42, lowercase: true },
    emphasisBreak: true,
    autoEmphasis: true,
    in: { kind: 'rise', dur: 320, ease: 'outQuint', stagger: 100, amp: 0.5 },
    defaultAccent: '#e8b04c',
  }),
  p({
    id: 'sanduiche-min',
    name: 'Sanduíche Minúsculo',
    cat: 'Viral',
    font: 'manrope800',
    size: 0.08,
    lineHeight: 0.92,
    uppercase: false,
    fill: 'accent',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    mix: { font: 'worksans800', scale: 0.4 },
    emphasisBreak: true,
    autoEmphasis: true,
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.5 },
    defaultAccent: '#ffd60a',
  }),
  p({
    id: 'extensao-script',
    name: 'Extensão Script',
    cat: 'Viral',
    font: 'lobster',
    size: 0.084,
    lineHeight: 0.95,
    uppercase: false,
    fill: 'accent',
    glow: { color: 'accent', blur: 0.22 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.03, y: 0.05 },
    mix: { font: 'inter800', scale: 0.36 },
    emphasisBreak: true,
    autoEmphasis: true,
    in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 100, amp: 0.5 },
    defaultAccent: '#e01f2f',
  }),
  p({
    id: 'selo-verde',
    name: 'Selo Verde',
    cat: 'Viral',
    font: 'playfair900',
    size: 0.068,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffe9c4'],
      [0.55, '#e8b04c'],
      [1, '#8a5a10'],
    ],
    highlightStyle: 'box',
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', stagger: 80, amp: 0.7 },
    autoEmphasis: true,
    defaultAccent: '#2ebd59',
  }),
  p({
    id: 'vermelho-sangue',
    name: 'Vermelho Sangue',
    cat: 'Viral',
    font: 'kanit800',
    size: 0.082,
    lineHeight: 0.96,
    uppercase: false,
    fill: '#e8192c',
    glow: { color: '#a00f1c', blur: 0.3 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.9 },
    autoEmphasis: false,
    defaultPrimary: '#e8192c',
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'manchete-sub',
    name: 'Manchete Sub',
    cat: 'Viral',
    font: 'saira800',
    size: 0.07,
    lineHeight: 1.02,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    mix: { font: 'oswald600', scale: 0.3, spacing: 0.35 },
    emphasisBreak: true,
    autoEmphasis: true,
    in: { kind: 'mask-up', dur: 360, ease: 'outQuint', stagger: 100 },
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'faz-assim',
    name: 'Faz Assim',
    cat: 'Viral',
    font: 'inter800',
    size: 0.058,
    uppercase: false,
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    in: { kind: 'rise', dur: 260, ease: 'outCubic', stagger: 70, amp: 0.4 },
    autoEmphasis: true,
    defaultAccent: '#2ebd59',
  }),
  p({
    id: 'botao-cta',
    name: 'Botão CTA',
    cat: 'Viral',
    font: 'inter800',
    size: 0.056,
    uppercase: false,
    box: {
      mode: 'block',
      fill: 'accent',
      radius: 0.4,
      padX: 0.6,
      padY: 0.34,
      autoText: true,
      gradient: [
        [0, '#ffd9a0'],
        [1, '#ff8a00'],
      ],
      shadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.08 },
    },
    unit: 'block',
    in: { kind: 'pop', dur: 280, ease: 'outBack' },
    autoEmphasis: false,
    defaultAccent: '#ff8a00',
  }),
  p({
    id: 'pilula-dourada',
    name: 'Pílula Dourada',
    cat: 'Viral',
    font: 'inter800',
    size: 0.05,
    uppercase: false,
    box: {
      mode: 'line',
      fill: 'rgba(18,14,6,0.78)',
      radius: 0.6,
      padX: 0.55,
      padY: 0.26,
      border: { color: '#e8b04c', width: 0.035 },
    },
    in: { kind: 'fade', dur: 260, ease: 'outQuad' },
    unit: 'block',
    autoEmphasis: true,
    defaultAccent: '#e8b04c',
  }),
  p({
    id: 'callout-pilula',
    name: 'Callout Pílula',
    cat: 'Viral',
    font: 'inter800',
    size: 0.05,
    uppercase: false,
    box: {
      mode: 'line',
      fill: '#ffffff',
      radius: 0.55,
      padX: 0.5,
      padY: 0.24,
      autoText: true,
      shadow: { color: 'rgba(0,0,0,0.35)', x: 0, y: 0.07 },
    },
    highlightStyle: 'box',
    in: { kind: 'pop', dur: 260, ease: 'outBackSoft' },
    unit: 'block',
    autoEmphasis: true,
    defaultAccent: '#e8192c',
  }),
  p({
    id: 'caixa-meio',
    name: 'Meio Boxado',
    cat: 'Viral',
    font: 'montserrat800',
    size: 0.058,
    uppercase: false,
    box: {
      mode: 'line',
      fill: '#2e9e6b',
      radius: 0.06,
      padX: 0.4,
      padY: 0.16,
      firstLineOnly: true,
    },
    lineAccent: undefined,
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.1, x: 0, y: 0.03 },
    unit: 'block',
    in: { kind: 'rise', dur: 280, ease: 'outQuint', stagger: 90, amp: 0.4 },
    autoEmphasis: false,
    defaultAccent: '#2e9e6b',
  }),
  p({
    id: 'azul-clean-glow',
    name: 'Azul Clean Glow',
    cat: 'Viral',
    font: 'montserrat800',
    size: 0.064,
    spacing: 0.04,
    fill: '#bfe9ff',
    glow: { color: '#57b6ff', blur: 0.3 },
    unit: 'block',
    in: { kind: 'fade', dur: 300, ease: 'outQuad' },
    out: { kind: 'fade', dur: 200 },
    autoEmphasis: false,
    defaultPrimary: '#bfe9ff',
    defaultAccent: '#57b6ff',
  }),
  p({
    id: 'derretido',
    name: 'Derretido',
    cat: 'Cartoon',
    font: 'modak',
    size: 0.078,
    lineHeight: 1.04,
    fill: 'accent',
    stroke: { color: '#2ebd59', width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.04, y: 0.06 },
    loop: { kind: 'pulse', amp: 0.04, freq: 1.2 },
    in: { kind: 'squash', dur: 380, ease: 'elastic', stagger: 110 },
    autoEmphasis: false,
    defaultAccent: '#ffd60a',
  }),
  p({
    id: 'bolha-brilho',
    name: 'Bolha Brilho',
    cat: 'Cartoon',
    font: 'modak',
    size: 0.074,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#b8f1ff'],
      [0.5, '#4fc3ee'],
      [1, '#1a8ac0'],
    ],
    stroke: { color: '#ffffff', width: 0.05 },
    shine: { period: 2000, alpha: 0.8 },
    hardShadow: { color: 'rgba(0,40,70,0.45)', x: 0.04, y: 0.06 },
    in: { kind: 'pop', dur: 460, ease: 'elastic', stagger: 100 },
    autoEmphasis: false,
    defaultAccent: '#4fc3ee',
  }),
  p({
    id: 'pixel-3d',
    name: 'Pixel 3D',
    cat: 'Glitch',
    font: 'silkscreen700',
    size: 0.058,
    fill: '#bfe3ff',
    chroma: { amp: 0.05, colors: ['#ff4fd8', '#4fc3ff'] },
    extrude: { color: '#274a86', x: 0.06, y: 0.07, steps: 5 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.08 },
    unit: 'block',
    in: { kind: 'glitch', dur: 340, ease: 'outCubic', amp: 1.2 },
    autoEmphasis: false,
    defaultPrimary: '#bfe3ff',
    defaultAccent: '#4fc3ff',
  }),
  p({
    id: 'letras-alternadas',
    name: 'Letras Alternadas',
    cat: 'Cartoon',
    font: 'luckiest',
    size: 0.068,
    unit: 'char',
    charColorCycle: ['#ff5db1', '#ffffff'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 22 },
    autoEmphasis: false,
    defaultAccent: '#ff5db1',
  }),
  p({
    id: 'flicker-vibrante',
    name: 'Flicker Vibrante',
    cat: 'Cartoon',
    font: 'ranchers',
    size: 0.07,
    unit: 'char',
    charColorCycle: ['#ff9f1a', '#ff9f1a', '#ffffff'],
    charOutlineRatio: 0.4,
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.05 },
    loop: { kind: 'flicker', amp: 0.3, freq: 8 },
    in: { kind: 'pop', dur: 240, ease: 'outBackSoft', stagger: 26 },
    autoEmphasis: false,
    defaultAccent: '#ff9f1a',
  }),
  p({
    id: 'estencil',
    name: 'Estêncil Listrado',
    cat: 'Viral',
    font: 'staatliches',
    size: 0.08,
    spacing: 0.03,
    patternFill: { colors: ['rgba(0,0,0,0)', '#ffffff'], scale: 0.9, speed: 0.6, style: 'stripes' },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.1, x: 0, y: 0.03 },
    unit: 'block',
    in: { kind: 'wipe', dur: 420, ease: 'outExpo', stagger: 90 },
    autoEmphasis: false,
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'paragrafo-vermelho',
    name: 'Parágrafo Vermelho',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.054,
    uppercase: false,
    box: { mode: 'line', fill: '#e8192c', radius: 0.04, padX: 0.38, padY: 0.16, skew: -3 },
    in: { kind: 'wipe', dur: 340, ease: 'outExpo', stagger: 90 },
    unit: 'block',
    autoEmphasis: false,
    defaultAccent: '#e8192c',
  }),

  // ─── FIDELIDADE às 34 refs da rodada 12 ──────────────────────────────────
  p({ id: 'automatico-arcoiris', name: 'Automático Arco-íris', cat: 'Viral', font: 'inter800', size: 0.062, lineHeight: 0.98, uppercase: false, hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.03, y: 0.05 }, highlightFont: 'kaushan', highlightGradient: [[0, '#ff5db1'], [0.5, '#a05ae0'], [1, '#3ab7ff']], highlightScale: 1.35, glow: { color: '#a05ae0', blur: 0.2 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.5 }, defaultAccent: '#a05ae0' }),
  p({ id: 'gigante-transparente', name: 'Gigante Transparente', cat: 'Viral', font: 'leaguegothic', size: 0.13, lineHeight: 0.9, fill: 'rgba(210,228,255,0.55)', shadow: { color: 'rgba(0,0,0,0.35)', blur: 0.08, x: 0, y: 0.03 }, unit: 'block', in: { kind: 'zoom-out', dur: 320, ease: 'outQuint', amp: 0.5 }, autoEmphasis: false, defaultAccent: '#d2e4ff' }),
  p({ id: 'tutorial-amarelo', name: 'Tutorial Amarelo', cat: 'Viral', font: 'passion700', size: 0.068, lineHeight: 1.0, fill: 'accent', hardShadow: { color: '#0a0a0a', x: 0.07, y: 0.09 }, unit: 'block', in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 0.9 }, autoEmphasis: false, defaultAccent: '#ffd60a' }),
  p({ id: 'serif-inline', name: 'Serif Inline', cat: 'Viral', font: 'inter800', size: 0.058, uppercase: false, highlightFont: 'playfair900i', shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 }, in: { kind: 'rise', dur: 280, ease: 'outQuint', stagger: 70, amp: 0.4 }, autoEmphasis: true, defaultAccent: '#ffffff' }),
  p({ id: 'fofo-doodle', name: 'Fofo Rabiscado', cat: 'Viral', font: 'fredoka600', size: 0.064, lineHeight: 1.04, stack: true, colorCycle: ['#ffffff', '#f9a8d4', '#c4b5fd', '#86efac'], doodles: { color: '#ffd60a' }, hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.05 }, in: { kind: 'pop', dur: 360, ease: 'outBackSoft', stagger: 110 }, autoEmphasis: false, defaultAccent: '#f9a8d4' }),
  p({ id: 'davinci-3d', name: 'Pack Virais 3D', cat: 'Viral', font: 'archivo', size: 0.072, lineHeight: 0.96, fill: 'gradient', gradientStops: [[0, '#ffffff'], [0.5, '#dfe4ea'], [1, '#aab3bd']], extrude: { color: '#3a3f47', x: 0.045, y: 0.05, steps: 5 }, highlightFont: 'dancing700', highlightGradient: [[0, '#ffd9a0'], [0.5, '#ff9f2e'], [1, '#e06a00']], highlightScale: 1.3, mix: { font: 'oswald600', scale: 0.36 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'zoom-out', dur: 320, ease: 'outQuint', amp: 0.8 }, defaultAccent: '#ff9f2e' }),
  p({ id: 'tijolos', name: 'Tijolos', cat: 'Máquina', font: 'pressstart', size: 0.052, lineHeight: 1.3, patternFill: { colors: ['#d98c4a', '#382214'], scale: 1.2, speed: 0, style: 'bricks' }, hardShadow: { color: 'rgba(0,0,0,0.6)', x: 0.06, y: 0.06 }, unit: 'block', in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 0.7 }, autoEmphasis: false, defaultAccent: '#d98c4a' }),
  p({ id: 'motivacional', name: 'Motivacional', cat: 'Minimal', font: 'montserrat800', size: 0.05, lineHeight: 1.18, stack: true, shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 }, out: { kind: 'fade', dur: 220 }, in: { kind: 'fade', dur: 320, ease: 'outQuad', stagger: 90 }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'colagem-editorial', name: 'Colagem Editorial', cat: 'Viral', font: 'leaguegothic', size: 0.08, lineHeight: 0.92, highlightFont: 'fraunces900i', highlightScale: 1.15, highlightColor: '#ffffff', mix: { font: 'kaushan', scale: 0.42, lowercase: true, color: 'accent', dy: 0.12 }, shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'rise', dur: 320, ease: 'outQuint', stagger: 100, amp: 0.5 }, defaultAccent: '#ff5db1' }),
  p({ id: 'grunge-carimbo', name: 'Grunge Carimbo', cat: 'Viral', font: 'archivo', size: 0.085, lineHeight: 0.96, patternFill: { colors: ['#e8300f', 'rgba(60,10,0,0.4)'], scale: 1.3, speed: 0.3, style: 'grunge' }, wordRotateJitter: 1.5, unit: 'block', in: { kind: 'zoom-out', dur: 220, ease: 'outQuint', amp: 1.4 }, autoEmphasis: true, highlightColor: '#f8ee1c', defaultAccent: '#f8ee1c' }),
  p({ id: 'grunge-amarelo', name: 'Grunge Amarelo', cat: 'Viral', font: 'archivo', size: 0.09, lineHeight: 0.94, patternFill: { colors: ['#f5e814', 'rgba(90,70,0,0.35)'], scale: 1.3, speed: 0.3, style: 'grunge' }, echoes: [{ pos: 'behind', scale: 1.35, color: '#ffffff', outline: true, alpha: 0.4 }], unit: 'block', in: { kind: 'squash', dur: 260, ease: 'outBack' }, autoEmphasis: false, defaultAccent: '#f5e814' }),
  p({ id: 'neither-riscado', name: 'Riscado Inline', cat: 'Viral', font: 'inter800', size: 0.06, highlightStyle: 'box', strikeOthers: true, hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.05 }, in: { kind: 'fade', dur: 220, ease: 'outQuad', stagger: 60 }, autoEmphasis: true, defaultAccent: '#e8192c' }),
  // Print aprovado pelo Silas (31.08): caixa PRETA solida colada no texto,
  // branco pesado em caixa alta, uma linha so. Nada de brilho, nada de
  // destaque automatico pintando palavra de outra cor — e o ponto do modelo.
  // ⚠ Nome "Preta Solida" de proposito: ja existe uma "Caixa Preta" na
  // categoria Headline (hl-caixa-preta), e duas com o mesmo nome na galeria
  // e' impossivel de distinguir. A diferenca real: aquela tem borda clara e
  // texto de contraste automatico; esta e preto puro, sem borda.
  p({
    id: 'preta-solida',
    name: 'Preta Sólida',
    cat: 'Destaque',
    font: 'montserrat900',
    size: 0.056,
    uppercase: true,
    lineHeight: 1.06,
    fill: WHITE,
    box: { mode: 'block', fill: '#000000', radius: 0.1, padX: 0.5, padY: 0.34 },
    unit: 'block',
    in: { kind: 'fade', dur: 200, ease: 'outQuad' },
    out: { kind: 'fade', dur: 160 },
    autoEmphasis: false,
    defaultPrimary: WHITE,
    defaultAccent: WHITE,
  }),
  p({ id: 'lower-third-claro', name: 'Lower Third Claro', cat: 'Destaque', font: 'barlow800', size: 0.05, box: { mode: 'line', fill: '#ffffff', radius: 0.04, padX: 0.45, padY: 0.2, autoText: true, border: { color: 'accent', width: 0.04 } }, mix: { font: 'oswald600', scale: 0.42 }, emphasisBreak: true, unit: 'block', in: { kind: 'slide-left', dur: 300, ease: 'outExpo', amp: 1 }, autoEmphasis: true, defaultAccent: '#ffd60a' }),
  p({ id: 'lower-third-ouro', name: 'Lower Third Ouro', cat: 'Destaque', font: 'barlow800', size: 0.052, box: { mode: 'block', fill: 'rgba(12,10,6,0.85)', radius: 0.06, padX: 0.5, padY: 0.3, border: { color: 'accent', width: 0.045 } }, mix: { font: 'oswald600', scale: 0.4 }, emphasisBreak: true, unit: 'block', in: { kind: 'wipe', dur: 340, ease: 'outExpo' }, autoEmphasis: true, defaultAccent: '#e8b04c' }),
  p({ id: 'verde-realidade', name: 'Verde Realidade', cat: 'Viral', font: 'montserrat800', size: 0.06, lineAccent: 'last', bar: { color: 'accent', thickness: 0.05, skew: 0 }, shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 }, unit: 'block', in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.4 }, autoEmphasis: false, defaultAccent: '#2edb84' }),
  p({ id: 'faixa-suave', name: 'Faixa Suave', cat: 'Destaque', font: 'inter800', size: 0.054, uppercase: false, box: { mode: 'line', fill: 'rgba(28,22,26,0.55)', radius: 0.3, padX: 0.55, padY: 0.26 }, unit: 'block', in: { kind: 'fade', dur: 280, ease: 'outQuad' }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'barra-branca-solida', name: 'Barra Branca', cat: 'Destaque', font: 'montserrat800', size: 0.054, box: { mode: 'line', fill: '#ffffff', radius: 0.02, padX: 0.45, padY: 0.2, autoText: true }, unit: 'block', in: { kind: 'wipe', dur: 300, ease: 'outExpo' }, autoEmphasis: false, defaultAccent: '#111111' }),
  p({ id: 'keynote', name: 'Keynote', cat: 'Minimal', font: 'dmsans900', size: 0.062, uppercase: false, shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 }, unit: 'block', in: { kind: 'fade', dur: 340, ease: 'outQuad' }, out: { kind: 'fade', dur: 240 }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'fade-base', name: 'Fade Base', cat: 'Minimal', font: 'dmsans900', size: 0.078, uppercase: false, fill: 'gradient', gradientStops: [[0, '#ffffff'], [0.55, '#ffffff'], [1, 'rgba(255,255,255,0)']], unit: 'block', in: { kind: 'rise', dur: 360, ease: 'outQuint', amp: 0.4 }, out: { kind: 'fade', dur: 240 }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'lavanda', name: 'Lavanda', cat: 'Minimal', font: 'dmsans900', size: 0.074, uppercase: false, fill: 'gradient', gradientStops: [[0, '#f4f1ff'], [0.6, '#c9bcf2'], [1, '#8f7ad8']], glow: { color: '#8f7ad8', blur: 0.22 }, unit: 'block', in: { kind: 'fade', dur: 340, ease: 'outQuad' }, out: { kind: 'fade', dur: 240 }, autoEmphasis: false, defaultAccent: '#c9bcf2' }),
  p({ id: 'vintage-editar', name: 'Vintage Editar', cat: 'Viral', font: 'inter800', size: 0.056, uppercase: false, fill: '#e8dcc4', chroma: { amp: 0.014 }, highlightFont: 'fraunces900i', highlightScale: 1.8, highlightColor: '#e8dcc4', shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 90, amp: 0.8 }, defaultPrimary: '#e8dcc4', defaultAccent: '#e8dcc4' }),
  p({ id: 'script-duo', name: 'Script Duo', cat: 'Viral', font: 'greatvibes', size: 0.082, lineHeight: 0.95, uppercase: false, mix: { font: 'worksans800', scale: 0.4 }, shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 100, amp: 0.4 }, defaultAccent: '#ffffff' }),
  p({ id: 'caixas-azuis', name: 'Caixas Azuis', cat: 'Destaque', font: 'inter800', size: 0.054, uppercase: false, box: { mode: 'line', fill: '#4a7fb5', radius: 0.08, padX: 0.4, padY: 0.18 }, highlightFont: 'playfair900i', unit: 'block', in: { kind: 'rise', dur: 280, ease: 'outQuint', stagger: 80, amp: 0.4 }, autoEmphasis: true, defaultAccent: '#ffffff' }),
  p({ id: 'obras-kinetic', name: 'Obras Kinetic', cat: 'Kinetic', font: 'inter800', size: 0.064, lineHeight: 0.9, uppercase: false, stack: true, sizeCycle: [0.78, 1.22], shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 }, in: { kind: 'rise', dur: 280, ease: 'outQuint', stagger: 90, amp: 0.5 }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'representa-verde', name: 'Representa', cat: 'Viral', font: 'archivo', size: 0.06, lineHeight: 1.06, box: { mode: 'line', fill: 'accent', radius: 0, padX: 0.4, padY: 0.12, autoText: true, fullBleed: true, emphasisLineOnly: true }, mix: { font: 'oswald600', scale: 0.44 }, emphasisBreak: true, autoEmphasis: true, unit: 'block', in: { kind: 'wipe', dur: 320, ease: 'outExpo', stagger: 90 }, defaultAccent: '#2edb84' }),
  p({ id: 'brush-city', name: 'Brush City', cat: 'Viral', font: 'kaushan', size: 0.08, lineHeight: 0.95, uppercase: false, fill: 'accent', hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 }, mix: { font: 'greatvibes', scale: 0.44, lowercase: true }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'skew-slide', dur: 300, ease: 'outExpo', stagger: 90 }, defaultAccent: '#f5e814' }),
  p({ id: 'plugin-azul', name: 'Plug-in Azul', cat: 'Viral', font: 'inter800', size: 0.06, uppercase: false, highlightStyle: 'box', highlightScale: 1.2, hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'rise', dur: 280, ease: 'outQuint', stagger: 90, amp: 0.5 }, defaultAccent: '#3aa0e8' }),
  p({ id: 'poster-esquerda', name: 'Pôster Esquerda', cat: 'Impacto', font: 'archivo', size: 0.078, lineHeight: 0.96, align: 'left', stack: true, shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.08, x: 0, y: 0.03 }, in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 90 }, autoEmphasis: false, defaultAccent: '#ffffff' }),
  p({ id: 'esperto-creme', name: 'Creme Contorno', cat: 'Viral', font: 'archivo', size: 0.062, fill: '#e8dcc0', stroke: { color: '#2a2118', width: 0.09 }, hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.05 }, unit: 'block', in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 0.8 }, autoEmphasis: false, defaultPrimary: '#e8dcc0', defaultAccent: '#ffd60a' }),
  p({ id: 'videos-viral-script', name: 'Videos Viral', cat: 'Viral', font: 'greatvibes', size: 0.088, lineHeight: 0.9, uppercase: false, mix: { font: 'inter800', scale: 0.3, accentLast: true, dy: 0.1 }, shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 100, amp: 0.4 }, defaultAccent: '#2edb84' }),
  p({ id: 'cabeca-gigante', name: 'Cabeça Gigante', cat: 'Viral', font: 'titan', size: 0.06, lineHeight: 0.98, uppercase: false, stroke: { color: '#ffffff', width: 0.05 }, hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 }, highlightGradient: [[0, '#b8f5c8'], [0.5, '#3ddc64'], [1, '#0e8a26']], highlightScale: 1.6, mix: { font: 'marker', scale: 0.5, lowercase: true }, emphasisBreak: true, autoEmphasis: true, in: { kind: 'pop', dur: 320, ease: 'outBack', stagger: 100 }, defaultAccent: '#3ddc64' }),
  p({ id: 'frases-chave', name: 'Frases Chave', cat: 'Viral', font: 'saira800', size: 0.06, lineHeight: 1.0, lineAccent: 'last', sideBar: { color: 'primary', width: 0.09 }, hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.03, y: 0.04 }, unit: 'block', in: { kind: 'slide-left', dur: 280, ease: 'outExpo', stagger: 70, amp: 1 }, autoEmphasis: false, defaultAccent: '#ffd60a' }),

  // ─── extras com as fontes novas (espalhados nas categorias) ──────────────
  p({
    id: 'cyber',
    name: 'Cyber',
    cat: 'Glitch',
    font: 'orbitron800',
    size: 0.06,
    spacing: 0.04,
    chroma: { amp: 0.035, flicker: true },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.03, y: 0.04 },
    unit: 'block',
    in: { kind: 'glitch', dur: 380, ease: 'outCubic', amp: 1.3 },
    autoEmphasis: true,
    defaultAccent: CYAN,
  }),
  p({
    id: 'speed',
    name: 'Speed',
    cat: 'Kinetic',
    font: 'fasterone',
    size: 0.062,
    in: { kind: 'slide-left', dur: 280, ease: 'outExpo', stagger: 60, amp: 1.4 },
    out: { kind: 'fade', dur: 140 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.05, y: 0.04 },
    loop: { kind: 'shake', amp: 0.02, freq: 7 },
    autoEmphasis: true,
    defaultAccent: RED,
  }),
  p({
    id: 'retro-game',
    name: 'Retro Game',
    cat: 'Máquina',
    font: 'pressstart',
    size: 0.042,
    lineHeight: 1.35,
    colorCycle: [LIME, '#ffffff', CYAN],
    hardShadow: { color: 'rgba(0,0,0,0.6)', x: 0.08, y: 0.08 },
    in: { kind: 'pop', dur: 160, ease: 'linear', stagger: 110 },
    defaultAccent: LIME,
  }),
  p({
    id: 'neon-tube',
    name: 'Tubo Neon',
    cat: 'Neon',
    font: 'monoton',
    size: 0.07,
    uppercase: true,
    spacing: 0.04,
    glow: { color: 'accent', blur: 0.45 },
    loop: { kind: 'flicker', amp: 0.45, freq: 10 },
    unit: 'block',
    in: { kind: 'fade', dur: 320, ease: 'outQuad' },
    autoEmphasis: false,
    defaultAccent: CYAN,
  }),
  p({
    id: 'militar',
    name: 'Militar',
    cat: 'Impacto',
    font: 'blackops',
    size: 0.062,
    fill: '#d7e4cf',
    box: { mode: 'line', fill: 'rgba(10,18,8,0.8)', radius: 0.04, padX: 0.4, padY: 0.16 },
    in: { kind: 'zoom-out', dur: 200, ease: 'outQuint', amp: 1.8 },
    blockRotateJitter: 2,
    autoEmphasis: true,
    highlightColor: '#9bff6b',
    defaultPrimary: '#d7e4cf',
    defaultAccent: '#9bff6b',
  }),
  p({
    id: 'placar',
    name: 'Placar',
    cat: 'Destaque',
    font: 'squada',
    size: 0.066,
    colorCycle: ['primary', 'accent'],
    box: { mode: 'line', fill: 'rgba(0,0,0,0.78)', radius: 0.08, padX: 0.42, padY: 0.16 },
    unit: 'block',
    in: { kind: 'wipe', dur: 340, ease: 'outExpo', stagger: 80 },
    defaultAccent: YELLOW,
  }),

  // ─── CARTOON ──────────────────────────────────────────────────────────────
  p({
    id: 'cartoon-pop',
    name: 'Cartoon Pop',
    cat: 'Cartoon',
    font: 'luckiest',
    size: 0.066,
    lineHeight: 1.04,
    colorCycle: [YELLOW, CYAN, PINK],
    stroke: { color: INK, width: 0.16 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.05, y: 0.07 },
    wordRotateJitter: 2,
    in: { kind: 'pop', dur: 420, ease: 'elastic', stagger: 100 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'comic-boom',
    name: 'Comic Boom',
    cat: 'Cartoon',
    font: 'bangers',
    size: 0.078,
    lineHeight: 1.02,
    spacing: 0.02,
    fill: 'accent',
    stroke: { color: INK, width: 0.1 },
    extrude: { color: INK, x: 0.04, y: 0.045, steps: 3 },
    wordRotateJitter: 3,
    in: { kind: 'rotate-in', dur: 300, ease: 'outBack', stagger: 90, amp: 1 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    defaultAccent: YELLOW,
  }),
  p({
    id: 'bubble',
    name: 'Bubble',
    cat: 'Cartoon',
    font: 'titan',
    size: 0.066,
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.2 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.05, y: 0.08 },
    in: { kind: 'pop', dur: 460, ease: 'elastic', stagger: 100 },
    autoEmphasis: true,
    highlightColor: YELLOW,
    defaultAccent: PINK,
  }),
  p({
    id: 'candy',
    name: 'Candy',
    cat: 'Cartoon',
    font: 'fredoka600',
    size: 0.064,
    colorCycle: ['#ff9ff3', '#feca57', '#54a0ff', '#ff6b6b'],
    stroke: { color: '#ffffff', width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.35)', x: 0.04, y: 0.06 },
    in: { kind: 'drop', dur: 340, ease: 'bounce', stagger: 90, amp: 1 },
    defaultAccent: '#feca57',
  }),
  p({
    id: 'gordinha',
    name: 'Gordinha',
    cat: 'Cartoon',
    font: 'modak',
    size: 0.078,
    lineHeight: 1.05,
    fill: 'accent',
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.05, y: 0.07 },
    in: { kind: 'squash', dur: 380, ease: 'elastic', stagger: 110 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    defaultAccent: ORANGE,
  }),
  p({
    id: 'terror',
    name: 'Terror',
    cat: 'Cartoon',
    font: 'creepster',
    size: 0.078,
    fill: '#c40f0f',
    glow: { color: '#7a0000', blur: 0.28 },
    loop: { kind: 'shake', amp: 0.03, freq: 5 },
    in: { kind: 'drop', dur: 380, ease: 'bounce', stagger: 110, amp: 1.2 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    defaultPrimary: '#c40f0f',
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'quadrinho',
    name: 'Quadrinho',
    cat: 'Cartoon',
    font: 'luckiest',
    size: 0.058,
    box: { mode: 'word', fill: '#ffffff', radius: 0.12, padX: 0.26, padY: 0.16, skew: -4, autoText: true, cycle: ['accent', '#ffffff'], shadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.07 } },
    wordRotateJitter: 2.5,
    in: { kind: 'pop', dur: 280, ease: 'outBack', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),

  // ─── ESTILO (premium serif/script) ───────────────────────────────────────
  p({
    id: 'fraunces-editorial',
    name: 'Fraunces',
    cat: 'Estilo',
    font: 'fraunces900',
    size: 0.072,
    lineHeight: 1.0,
    uppercase: false,
    emphasisBreak: true,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    mix: { font: 'fraunces900i', scale: 0.5, lowercase: true, color: 'accent' },
    in: { kind: 'mask-up', dur: 400, ease: 'outQuint', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'bodoni-fashion',
    name: 'Fashion',
    cat: 'Estilo',
    font: 'bodoni800',
    size: 0.06,
    spacing: 0.1,
    frameLines: { color: 'primary', thickness: 0.03, gap: 0.5 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.03 },
    unit: 'block',
    in: { kind: 'tracking-in', dur: 460, ease: 'outExpo', amp: 0.6 },
    out: { kind: 'fade', dur: 220 },
    autoEmphasis: false,
    defaultAccent: WHITE,
  }),
  p({
    id: 'assinatura-neon',
    name: 'Assinatura Neon',
    cat: 'Estilo',
    font: 'mrdafoe',
    size: 0.08,
    uppercase: false,
    glow: { color: 'accent', blur: 0.4 },
    loop: { kind: 'flicker', amp: 0.35, freq: 9 },
    unit: 'block',
    in: { kind: 'fade', dur: 300, ease: 'outQuad' },
    autoEmphasis: false,
    defaultAccent: PINK,
  }),
  p({
    id: 'convite',
    name: 'Convite',
    cat: 'Estilo',
    font: 'greatvibes',
    size: 0.082,
    uppercase: false,
    shine: { period: 2600, alpha: 0.6 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    in: { kind: 'rise', dur: 380, ease: 'outQuint', stagger: 110, amp: 0.4 },
    out: { kind: 'fade', dur: 220 },
    autoEmphasis: false,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'prata-fina',
    name: 'Prata Fina',
    cat: 'Estilo',
    font: 'prata',
    size: 0.06,
    uppercase: false,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'blur', dur: 380, ease: 'outCubic', amp: 0.8 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    autoEmphasis: true,
    defaultAccent: '#d9e2ec',
  }),
  p({
    id: 'epico',
    name: 'Épico',
    cat: 'Estilo',
    font: 'cinzel800',
    size: 0.062,
    spacing: 0.05,
    fill: 'gradient',
    gradientStops: [
      [0, '#fdf3d0'],
      [0.45, '#eac859'],
      [0.62, '#9c7410'],
      [1, '#e3b93e'],
    ],
    smoke: { alpha: 0.35 },
    shine: { period: 3000, alpha: 0.6 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.04, y: 0.05 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 420, ease: 'outQuint', amp: 0.7 },
    autoEmphasis: false,
    defaultAccent: '#eac859',
  }),
  p({
    id: 'jornal',
    name: 'Manchete',
    cat: 'Estilo',
    font: 'rozha',
    size: 0.066,
    uppercase: false,
    bar: { color: 'accent', thickness: 0.1, skew: 0 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 380, ease: 'outQuint', stagger: 100 },
    autoEmphasis: true,
    defaultAccent: RED,
  }),

  // ─── PREMIUM ──────────────────────────────────────────────────────────────
  p({
    id: 'auto-hype',
    name: 'Auto Hype',
    cat: 'Premium',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 80 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    autoEmphasis: true,
    highlightScale: 1.42,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'ouro',
    name: 'Ouro',
    cat: 'Premium',
    font: 'anton',
    size: 0.072,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff8dc'],
      [0.3, '#ffe08a'],
      [0.52, '#f0b429'],
      [0.62, '#8a5a00'],
      [0.72, '#e8a824'],
      [1, '#6b4300'],
    ],
    shine: { period: 2400, alpha: 0.8 },
    stroke: { color: '#4a3200', width: 0.05 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 320, ease: 'outQuint', amp: 0.9 },
    defaultAccent: '#ffd970',
  }),
  p({
    id: 'chrome',
    name: 'Chrome',
    cat: 'Premium',
    font: 'archivo',
    size: 0.066,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.42, '#dfe6ee'],
      [0.52, '#8d99a6'],
      [0.6, '#eef3f8'],
      [1, '#7a8794'],
    ],
    shine: { period: 2000, alpha: 0.9 },
    stroke: { color: '#232830', width: 0.06 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.08 },
    in: { kind: 'drop', dur: 300, ease: 'outBack', stagger: 90, amp: 1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'brilho',
    name: 'Brilho',
    cat: 'Premium',
    font: 'inter800',
    size: 0.058,
    shine: { period: 1700, alpha: 0.9 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 60, amp: 0.6 },
    out: { kind: 'fade', dur: 160 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'long-shadow',
    name: 'Long Shadow',
    cat: 'Premium',
    font: 'montserrat900',
    size: 0.064,
    extrude: { color: 'rgba(0,0,0,0.4)', x: 0.09, y: 0.09, steps: 12, fade: true },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 80 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'duotone',
    name: 'Duotone',
    cat: 'Premium',
    font: 'anton',
    size: 0.074,
    fill: 'gradient',
    gradientStops: [
      [0, 'primary'],
      [0.5, 'primary'],
      [0.505, 'accent'],
      [1, 'accent'],
    ],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'stretch-x', dur: 300, ease: 'outBack', amp: 1.2 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'metal-slam',
    name: 'Metal Slam',
    cat: 'Premium',
    font: 'anton',
    size: 0.078,
    fill: 'gradient',
    gradientStops: [
      [0, '#f8fafc'],
      [0.45, '#cbd5e1'],
      [0.52, '#64748b'],
      [0.6, '#e2e8f0'],
      [1, '#475569'],
    ],
    shine: { period: 2600, alpha: 0.75 },
    chroma: { amp: 0.016 },
    hardShadow: { color: 'rgba(0,0,0,0.6)', x: 0.06, y: 0.09 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 240, ease: 'outQuint', amp: 2 },
    out: { kind: 'zoom', dur: 140 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'ouro-editorial',
    name: 'Ouro Editorial',
    cat: 'Premium',
    font: 'playfair900',
    size: 0.062,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#fdf3d0'],
      [0.45, '#eac859'],
      [0.6, '#9c7410'],
      [0.72, '#e3b93e'],
      [1, '#7a5a08'],
    ],
    shine: { period: 3200, alpha: 0.65 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
    unit: 'block',
    in: { kind: 'blur-zoom', dur: 480, ease: 'outQuint', amp: 0.9 },
    out: { kind: 'fade', dur: 240 },
    defaultAccent: '#eac859',
  }),

  // ─── COR ──────────────────────────────────────────────────────────────────
  p({
    id: 'fogo',
    name: 'Fogo',
    cat: 'Cor',
    font: 'anton',
    size: 0.072,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3b0'],
      [0.4, '#ffb703'],
      [0.75, '#fb5607'],
      [1, '#d00000'],
    ],
    glow: { color: '#ff7b00', blur: 0.32 },
    loop: { kind: 'flicker', amp: 0.3, freq: 10 },
    in: { kind: 'squash', dur: 280, ease: 'outBack', stagger: 90 },
    defaultAccent: '#ffb703',
  }),
  p({
    id: 'gelo',
    name: 'Gelo',
    cat: 'Cor',
    font: 'archivo',
    size: 0.066,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.55, '#bde0fe'],
      [1, '#4cc9f0'],
    ],
    aura: { color: '#4cc9f0', count: 3, width: 0.16, alpha: 0.35 },
    in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 80, amp: 1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'sunset',
    name: 'Sunset',
    cat: 'Cor',
    font: 'nunito900',
    size: 0.064,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffd6ff'],
      [0.5, '#ff8fab'],
      [1, '#ff5d8f'],
    ],
    stroke: { color: '#5a1836', width: 0.08 },
    loop: { kind: 'wave', amp: 0.06, freq: 1.3 },
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.7 },
    defaultAccent: '#ff8fab',
  }),
  p({
    id: 'carnaval',
    name: 'Carnaval',
    cat: 'Cor',
    font: 'nunito900',
    size: 0.062,
    colorCycle: [YELLOW, CYAN, PINK, LIME],
    stroke: { color: INK, width: 0.15 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.07 },
    wordRotateJitter: 2.5,
    in: { kind: 'pop', dur: 300, ease: 'outBack', stagger: 90 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'tamanhos',
    name: 'Tamanhos',
    cat: 'Cor',
    font: 'anton',
    size: 0.06,
    lineHeight: 1.06,
    sizeCycle: [0.82, 1.3, 1],
    colorCycle: ['primary', 'accent', 'primary'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'gigante',
    name: 'Gigante',
    cat: 'Cor',
    font: 'archivo',
    size: 0.058,
    lineHeight: 1.04,
    sizeCycle: [1, 1.45],
    colorCycle: ['primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 100, amp: 1.2 },
    defaultAccent: ORANGE,
  }),
  p({
    id: 'split-pop',
    name: 'Split Pop',
    cat: 'Cor',
    font: 'anton',
    size: 0.07,
    fill: 'gradient',
    gradientStops: [
      [0, 'primary'],
      [0.5, 'primary'],
      [0.505, 'accent'],
      [1, 'accent'],
    ],
    stroke: { color: INK, width: 0.09 },
    wordRotateJitter: 2,
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 90 },
    defaultAccent: CYAN,
  }),

  // ─── IMPACTO ──────────────────────────────────────────────────────────────
  p({
    id: 'pop-punch',
    autoEmphasis: true,
    name: 'Pop Punch',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.066,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 70 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
  }),
  p({
    id: 'extrude-slam',
    name: '3D Slam',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.068,
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', stagger: 80, amp: 1.4 },
    extrude: { color: 'accent', x: 0.055, y: 0.065, steps: 6 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.1, y: 0.12 },
    blockRotate: -2,
    defaultAccent: '#b45309',
  }),
  p({
    id: 'stomp',
    autoEmphasis: true,
    name: 'Stomp',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.07,
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 90, amp: 1.4 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.09 },
    blockRotate: -1.5,
  }),
  p({
    id: 'carimbo',
    autoEmphasis: true,
    name: 'Carimbo',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 180, ease: 'outQuint', amp: 2.2 },
    stroke: { color: 'accent', width: 0.1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    blockRotateJitter: 4,
    defaultAccent: RED,
  }),
  p({
    id: 'barra-impacto',
    autoEmphasis: true,
    name: 'Barra de Impacto',
    cat: 'Impacto',
    font: 'oswald600',
    size: 0.068,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'wipe', dur: 380, ease: 'outExpo', stagger: 90 },
    bar: { color: 'accent', thickness: 0.16, skew: -10 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    defaultAccent: RED,
  }),
  p({
    id: 'zoom-crush',
    autoEmphasis: true,
    name: 'Zoom Crush',
    cat: 'Impacto',
    font: 'anton',
    size: 0.082,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 1.9 },
    out: { kind: 'zoom', dur: 140 },
    stroke: { color: INK, width: 0.12 },
    chroma: { amp: 0.022 },
  }),
  p({
    id: 'slam-giro',
    autoEmphasis: true,
    name: 'Slam Giro',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'rotate-in', dur: 320, ease: 'outBack', stagger: 80, amp: 0.9 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.07 },
  }),
  p({
    id: 'soco-alternado',
    autoEmphasis: true,
    name: 'Soco Alternado',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.068,
    in: { kind: 'squash', dur: 260, ease: 'outBack', stagger: 110 },
    stroke: { color: INK, width: 0.16 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),

  // ─── KARAOKÊ ──────────────────────────────────────────────────────────────
  p({
    id: 'karaoke-fill',
    name: 'Karaokê Fill',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.06,
    karaoke: 'fill',
    unit: 'block',
    in: { kind: 'fade', dur: 140 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: LIME,
  }),
  p({
    id: 'palavra-box',
    name: 'Palavra Box',
    cat: 'Karaokê',
    font: 'inter800',
    size: 0.056,
    karaoke: 'word-box',
    unit: 'block',
    in: { kind: 'rise', dur: 200, ease: 'outCubic', amp: 0.45 },
    box: { mode: 'none', fill: 'accent', radius: 0.18, padX: 0.22, padY: 0.14, skew: -6, shadow: { color: 'rgba(0,0,0,0.45)', x: 0.06, y: 0.08 } },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'palavra-cor',
    name: 'Palavra Cor',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.062,
    karaoke: 'word-color',
    unit: 'block',
    in: { kind: 'pop', dur: 200, ease: 'outBackSoft' },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'karaoke-zoom',
    name: 'Karaokê Zoom',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.06,
    karaoke: 'word-zoom',
    unit: 'block',
    in: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'um-por-um',
    autoEmphasis: true,
    name: 'Um Por Um',
    cat: 'Karaokê',
    font: 'anton',
    size: 0.095,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'pop', dur: 150, ease: 'outBack' },
    stroke: { color: INK, width: 0.11 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.08 },
    blockRotateJitter: 2.5,
  }),
  p({
    id: 'solo-box',
    autoEmphasis: true,
    name: 'Solo Box',
    cat: 'Karaokê',
    font: 'archivo',
    size: 0.08,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'squash', dur: 200, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.16, padX: 0.4, padY: 0.22, skew: -7, autoText: true, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.11 } },
    blockRotateJitter: 3.5,
    highlightColor: YELLOW,
    defaultAccent: RED,
  }),
  p({
    id: 'karaoke-holofote',
    name: 'Holofote',
    cat: 'Karaokê',
    font: 'inter800',
    size: 0.06,
    karaoke: 'word-color',
    karaokeDim: 0.3,
    unit: 'block',
    in: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: WHITE,
  }),
  p({
    id: 'karaoke-caixa-sombra',
    name: 'Caixa Sombra',
    cat: 'Karaokê',
    font: 'archivo',
    size: 0.058,
    karaoke: 'word-box',
    karaokeDim: 0.5,
    unit: 'block',
    box: { mode: 'none', fill: 'accent', radius: 0.14, padX: 0.24, padY: 0.15, skew: -6, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.07, y: 0.09 } },
    in: { kind: 'rise', dur: 200, ease: 'outCubic', amp: 0.4 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.05 },
    defaultAccent: RED,
  }),
  p({
    id: 'karaoke-fill-ouro',
    name: 'Fill Dourado',
    cat: 'Karaokê',
    font: 'playfair900',
    size: 0.062,
    uppercase: false,
    karaoke: 'fill',
    unit: 'block',
    in: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: '#e8b04c',
  }),
  p({
    id: 'karaoke-zoom-neon',
    name: 'Zoom Neon',
    cat: 'Karaokê',
    font: 'bebas',
    size: 0.072,
    spacing: 0.02,
    karaoke: 'word-zoom',
    karaokeDim: 0.45,
    unit: 'block',
    glow: { color: 'accent', blur: 0.38 },
    in: { kind: 'fade', dur: 180 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'karaoke-sublinha-lime',
    name: 'Sublinha Grossa',
    cat: 'Karaokê',
    font: 'bigshoulders800',
    size: 0.066,
    karaoke: 'word-underline',
    karaokeDim: 0.55,
    unit: 'block',
    in: { kind: 'rise', dur: 220, ease: 'outCubic', amp: 0.5 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.03, y: 0.05 },
    defaultAccent: LIME,
  }),
  p({
    id: 'karaoke-pixel',
    name: 'Karaokê Pixel',
    cat: 'Karaokê',
    font: 'pressstart',
    size: 0.04,
    lineHeight: 1.4,
    karaoke: 'fill',
    unit: 'block',
    in: { kind: 'fade', dur: 140 },
    hardShadow: { color: 'rgba(0,0,0,0.6)', x: 0.08, y: 0.08 },
    defaultAccent: LIME,
  }),
  p({
    id: 'karaoke-script',
    name: 'Karaokê Script',
    cat: 'Karaokê',
    font: 'kaushan',
    size: 0.07,
    uppercase: false,
    karaoke: 'word-color',
    karaokeDim: 0.5,
    unit: 'block',
    in: { kind: 'rise', dur: 220, ease: 'outQuint', amp: 0.4 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    defaultAccent: PINK,
  }),
  p({
    id: 'karaoke-pill',
    name: 'Caixa Pill',
    cat: 'Karaokê',
    font: 'inter800',
    size: 0.054,
    uppercase: false,
    karaoke: 'word-box',
    unit: 'block',
    box: { mode: 'none', fill: 'accent', radius: 0.5, padX: 0.3, padY: 0.18 },
    in: { kind: 'rise', dur: 200, ease: 'outCubic', amp: 0.4 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'sublinha-ativa',
    name: 'Sublinha Ativa',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.058,
    karaoke: 'word-underline',
    unit: 'block',
    in: { kind: 'rise', dur: 220, ease: 'outCubic', amp: 0.5 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
    defaultAccent: LIME,
  }),

  // ─── GLITCH ───────────────────────────────────────────────────────────────
  p({
    id: 'glitch-brutal',
    autoEmphasis: true,
    name: 'Glitch Brutal',
    cat: 'Glitch',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'glitch', dur: 420, ease: 'outCubic', amp: 1.6 },
    chroma: { amp: 0.045, flicker: true },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
  }),
  p({
    id: 'glitch-rgb',
    autoEmphasis: true,
    name: 'Glitch RGB',
    cat: 'Glitch',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'glitch', dur: 420, ease: 'outQuad', stagger: 60, amp: 1.2 },
    chroma: { amp: 0.028 },
    glitchBands: true,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
  }),
  p({
    id: 'glitch-digital',
    autoEmphasis: true,
    name: 'Glitch Digital',
    cat: 'Glitch',
    font: 'anton',
    size: 0.072,
    unit: 'block',
    in: { kind: 'glitch', dur: 360, ease: 'outCubic', amp: 1.6 },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    stroke: { color: INK, width: 0.1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'vhs',
    autoEmphasis: true,
    name: 'VHS',
    cat: 'Glitch',
    font: 'inter800',
    size: 0.056,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'fade', dur: 200 },
    chroma: { amp: 0.05, flicker: true },
    loop: { kind: 'float', amp: 0.04, freq: 0.7 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0 },
  }),
  p({
    id: 'static-pop',
    autoEmphasis: true,
    name: 'Static Pop',
    cat: 'Glitch',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'pop', dur: 180, ease: 'outQuint', stagger: 60 },
    chroma: { amp: 0.03, flicker: true },
    loop: { kind: 'flicker', amp: 0.25, freq: 9 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: RED,
  }),

  // ─── DESTAQUE ─────────────────────────────────────────────────────────────
  p({
    id: 'poster-stack',
    autoEmphasis: true,
    name: 'Pôster',
    cat: 'Destaque',
    font: 'anton',
    size: 0.062,
    lineHeight: 1.02,
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    highlightScale: 1.5,
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-solida',
    autoEmphasis: true,
    name: 'Caixa Sólida',
    cat: 'Destaque',
    font: 'montserrat900',
    size: 0.058,
    unit: 'block',
    in: { kind: 'pop', dur: 260, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.2, padX: 0.5, padY: 0.3, skew: -4, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.1 } },
    fill: '#0f0f10',
    highlightColor: RED,
    defaultPrimary: INK,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-branca',
    autoEmphasis: true,
    name: 'Caixa Branca',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.054,
    unit: 'block',
    in: { kind: 'rise', dur: 260, ease: 'outBackSoft', amp: 0.5 },
    box: { mode: 'line', fill: '#ffffff', radius: 0.18, padX: 0.4, padY: 0.18, shadow: { color: 'rgba(0,0,0,0.35)', x: 0, y: 0.08 } },
    fill: '#111111',
    defaultPrimary: '#111111',
    defaultAccent: RED,
  }),
  p({
    id: 'empilhado',
    autoEmphasis: true,
    name: 'Empilhado',
    cat: 'Destaque',
    font: 'archivo',
    size: 0.054,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 100 },
    box: { mode: 'word', fill: '#111111', radius: 0.1, padX: 0.26, padY: 0.18, skew: -5, autoText: true, cycle: ['accent', '#141414', '#ffffff'], shadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.08 } },
    wordRotateJitter: 2.5,
    defaultAccent: RED,
  }),
  p({
    id: 'adesivo',
    autoEmphasis: true,
    name: 'Adesivo',
    cat: 'Destaque',
    font: 'nunito900',
    size: 0.062,
    in: { kind: 'pop', dur: 480, ease: 'elastic', stagger: 100 },
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.26 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.09 },
    wordRotateJitter: 3,
    highlightColor: YELLOW,
    defaultAccent: PINK,
  }),
  p({
    id: 'tarja-preta',
    autoEmphasis: true,
    name: 'Tarja Preta',
    cat: 'Destaque',
    font: 'oswald600',
    size: 0.06,
    unit: 'block',
    in: { kind: 'wipe', dur: 360, ease: 'outExpo', stagger: 80 },
    box: { mode: 'line', fill: 'rgba(0,0,0,0.85)', radius: 0.04, padX: 0.4, padY: 0.14, skew: -4 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chip-palavra',
    autoEmphasis: true,
    name: 'Chip Palavra',
    cat: 'Destaque',
    font: 'poppins800',
    size: 0.05,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 90 },
    box: { mode: 'word', fill: 'rgba(0,0,0,0.8)', radius: 0.3, padX: 0.3, padY: 0.2 },
    defaultAccent: LIME,
    highlightStyle: 'box',
  }),
  p({
    id: 'auto-box',
    name: 'Auto Box',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.056,
    in: { kind: 'rise', dur: 260, ease: 'outCubic', stagger: 70, amp: 0.45 },
    autoEmphasis: true,
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: LIME,
  }),
  p({
    id: 'marca-texto',
    autoEmphasis: true,
    name: 'Marca-Texto',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 280, ease: 'outCubic', stagger: 70, amp: 0.4 },
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'sublinhado-forte',
    autoEmphasis: true,
    name: 'Sublinhado',
    cat: 'Destaque',
    font: 'montserrat800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'fade', dur: 260, ease: 'outQuad', stagger: 60 },
    highlightStyle: 'underline',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: LIME,
  }),

  // ─── MINIMAL ──────────────────────────────────────────────────────────────
  p({
    id: 'fade-limpo',
    autoEmphasis: true,
    name: 'Fade Limpo',
    cat: 'Minimal',
    font: 'inter800',
    size: 0.052,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 320, ease: 'outQuad' },
    out: { kind: 'fade', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'sobe-suave',
    autoEmphasis: true,
    name: 'Sobe Suave',
    cat: 'Minimal',
    font: 'poppins800',
    size: 0.054,
    uppercase: false,
    in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 60, amp: 0.7 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'tracking-aberto',
    autoEmphasis: true,
    name: 'Tracking Aberto',
    cat: 'Minimal',
    font: 'montserrat800',
    size: 0.05,
    spacing: 0.06,
    unit: 'block',
    in: { kind: 'tracking-in', dur: 420, ease: 'outExpo', amp: 0.7 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'oswald-clean',
    autoEmphasis: true,
    name: 'Alto e Limpo',
    cat: 'Minimal',
    font: 'oswald600',
    size: 0.062,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'blur', dur: 300, ease: 'outCubic', amp: 0.8 },
    out: { kind: 'blur', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.14, x: 0, y: 0.05 },
  }),

  // ─── BOUNCE ───────────────────────────────────────────────────────────────
  p({
    id: 'bounce-elastico',
    autoEmphasis: true,
    name: 'Bounce Elástico',
    cat: 'Bounce',
    font: 'poppins800',
    size: 0.062,
    in: { kind: 'pop', dur: 560, ease: 'elastic', stagger: 90 },
    stroke: { color: INK, width: 0.13 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: PINK,
  }),
  p({
    id: 'jelly',
    autoEmphasis: true,
    name: 'Jelly',
    cat: 'Bounce',
    font: 'nunito900',
    size: 0.064,
    in: { kind: 'squash', dur: 420, ease: 'elastic', stagger: 100 },
    stroke: { color: INK, width: 0.15 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'quica-letra',
    autoEmphasis: true,
    name: 'Quica Letra',
    cat: 'Bounce',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'drop', dur: 340, ease: 'bounce', stagger: 26, amp: 1.1 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
  }),

  // ─── MÁQUINA ──────────────────────────────────────────────────────────────
  p({
    id: 'maquina',
    autoEmphasis: true,
    name: 'Máquina',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.05,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 900 },
    caret: 'bar',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: WHITE,
  }),
  p({
    id: 'terminal',
    autoEmphasis: true,
    name: 'Terminal',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.048,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 800 },
    caret: 'block',
    fill: '#4ade80',
    glow: { color: GREEN_TERM, blur: 0.4 },
    defaultPrimary: GREEN_TERM,
    defaultAccent: GREEN_TERM,
  }),
  p({
    id: 'digitada',
    autoEmphasis: true,
    name: 'Digitada',
    cat: 'Máquina',
    font: 'inter800',
    size: 0.054,
    uppercase: true,
    unit: 'block',
    in: { kind: 'typewriter', dur: 620 },
    caret: 'bar',
    box: { mode: 'line', fill: 'rgba(0,0,0,0.72)', radius: 0.16, padX: 0.34, padY: 0.16 },
    defaultAccent: ORANGE,
  }),

  // ─── FOCO ─────────────────────────────────────────────────────────────────
  p({
    id: 'blur-reveal',
    autoEmphasis: true,
    name: 'Blur Reveal',
    cat: 'Foco',
    font: 'poppins800',
    size: 0.058,
    in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 80, amp: 1 },
    out: { kind: 'blur', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'foco-cine',
    autoEmphasis: true,
    name: 'Foco Cine',
    cat: 'Foco',
    font: 'playfair900',
    size: 0.06,
    uppercase: false,
    unit: 'block',
    in: { kind: 'blur-zoom', dur: 520, ease: 'outQuint', amp: 1 },
    out: { kind: 'blur', dur: 260 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
  }),
  p({
    id: 'motion-slide',
    autoEmphasis: true,
    name: 'Motion Slide',
    cat: 'Foco',
    font: 'inter800',
    size: 0.056,
    in: { kind: 'slide-left', dur: 300, ease: 'outExpo', stagger: 55, amp: 1 },
    out: { kind: 'fade', dur: 150 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),

  // ─── REVEAL ───────────────────────────────────────────────────────────────
  p({
    id: 'mask-up',
    autoEmphasis: true,
    name: 'Mask Up',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.06,
    unit: 'block',
    in: { kind: 'mask-up', dur: 380, ease: 'outQuint', stagger: 110 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'cortina',
    autoEmphasis: true,
    name: 'Cortina',
    cat: 'Reveal',
    font: 'anton',
    size: 0.07,
    unit: 'block',
    in: { kind: 'wipe', dur: 420, ease: 'outExpo', stagger: 90 },
    out: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.1 },
  }),
  p({
    id: 'flip-belt',
    autoEmphasis: true,
    name: 'Flip 3D',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'flip', dur: 340, ease: 'outBack', stagger: 90 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: ORANGE,
  }),
  p({
    id: 'stretch-impact',
    autoEmphasis: true,
    name: 'Stretch',
    cat: 'Reveal',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'stretch-x', dur: 320, ease: 'outBack', amp: 1.6 },
    stroke: { color: INK, width: 0.11 },
  }),
  p({
    id: 'skew-kinetic',
    autoEmphasis: true,
    name: 'Skew Kinetic',
    cat: 'Reveal',
    font: 'poppins800',
    size: 0.06,
    in: { kind: 'skew-slide', dur: 300, ease: 'outExpo', stagger: 70 },
    out: { kind: 'fade', dur: 140 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0.03, y: 0.05 },
  }),

  // ─── NEON ─────────────────────────────────────────────────────────────────
  p({
    id: 'neon-brutal',
    autoEmphasis: true,
    name: 'Neon Brutal',
    cat: 'Neon',
    font: 'bebas',
    size: 0.086,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 240, ease: 'outQuint', amp: 0.9 },
    glow: { color: 'accent', blur: 0.5 },
    stroke: { color: '#ffffff', width: 0.045 },
    chroma: { amp: 0.02, flicker: true },
    loop: { kind: 'flicker', amp: 0.5, freq: 12 },
    defaultAccent: PINK,
  }),
  p({
    id: 'eco-neon',
    autoEmphasis: true,
    name: 'Eco Neon',
    cat: 'Neon',
    font: 'bebas',
    size: 0.082,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'fade', dur: 240, ease: 'outQuad' },
    aura: { color: 'accent', count: 4, width: 0.24, alpha: 0.5, pulse: true },
    glow: { color: 'accent', blur: 0.32 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'auto-neon',
    name: 'Neon Destaque',
    cat: 'Neon',
    font: 'bebas',
    size: 0.08,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 0.8 },
    glow: { color: 'accent', blur: 0.42 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    highlightScale: 1.2,
    loop: { kind: 'flicker', amp: 0.35, freq: 10 },
    defaultAccent: PINK,
  }),
  p({
    id: 'neon-pulse',
    autoEmphasis: true,
    name: 'Neon Pulse',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'fade', dur: 260, ease: 'outQuad' },
    loop: { kind: 'flicker', amp: 0.55, freq: 11 },
    glow: { color: 'accent', blur: 0.42 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'neon-rosa',
    autoEmphasis: true,
    name: 'Neon Rosa',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    in: { kind: 'pop', dur: 260, ease: 'outBackSoft', stagger: 80 },
    glow: { color: 'accent', blur: 0.4 },
    loop: { kind: 'pulse', amp: 0.05, freq: 1.6 },
    defaultAccent: PINK,
  }),
  p({
    id: 'luz-de-palco',
    autoEmphasis: true,
    name: 'Luz de Palco',
    cat: 'Neon',
    font: 'anton',
    size: 0.08,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    glow: { color: 'accent', blur: 0.52 },
    loop: { kind: 'pulse', amp: 0.04, freq: 1.1 },
    defaultAccent: YELLOW,
  }),

  // ─── KINETIC ──────────────────────────────────────────────────────────────
  p({
    id: 'duas-cores',
    name: 'Duas Cores',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'skew-slide', dur: 280, ease: 'outExpo', stagger: 80 },
    colorCycle: ['primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.045, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chroma-wave',
    autoEmphasis: true,
    name: 'Chroma Wave',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    chroma: { amp: 0.035 },
    loop: { kind: 'wave', amp: 0.07, freq: 1.4 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'onda',
    autoEmphasis: true,
    name: 'Onda',
    cat: 'Kinetic',
    font: 'nunito900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    loop: { kind: 'wave', amp: 0.09, freq: 1.6 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'shake-hype',
    autoEmphasis: true,
    name: 'Shake Hype',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 220, ease: 'outQuint', amp: 1 },
    loop: { kind: 'shake', amp: 0.05, freq: 8 },
    stroke: { color: INK, width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),
  p({
    id: 'float-suave',
    autoEmphasis: true,
    name: 'Float Suave',
    cat: 'Kinetic',
    font: 'poppins800',
    size: 0.056,
    uppercase: false,
    unit: 'block',
    in: { kind: 'rise', dur: 380, ease: 'outQuint', amp: 0.6 },
    loop: { kind: 'float', amp: 0.05, freq: 0.9 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'letra-viva',
    autoEmphasis: true,
    name: 'Letra Viva',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 22 },
    loop: { kind: 'wave', amp: 0.05, freq: 1.2 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: LIME,
  }),

  // ─── EDITORIAL ────────────────────────────────────────────────────────────
  p({
    id: 'editorial-destaque',
    autoEmphasis: true,
    name: 'Editorial Destaque',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'mask-up', dur: 420, ease: 'outQuint', stagger: 120 },
    highlightScale: 1.32,
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'editorial-serif',
    autoEmphasis: true,
    name: 'Editorial',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 420, ease: 'outQuad' },
    out: { kind: 'fade', dur: 240 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'vogue-mask',
    autoEmphasis: true,
    name: 'Vogue',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.06,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'mask-up', dur: 460, ease: 'outQuint', stagger: 130 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.03 },
  }),
  p({
    id: 'citacao',
    autoEmphasis: true,
    name: 'Citação',
    cat: 'Editorial',
    font: 'playfair900i',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 380, ease: 'outQuint', stagger: 80, amp: 0.5 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'rabisco',
    autoEmphasis: true,
    name: 'Rabisco',
    cat: 'Editorial',
    font: 'marker',
    size: 0.06,
    uppercase: false,
    in: { kind: 'rotate-in', dur: 300, ease: 'outBack', stagger: 100, amp: 0.5 },
    wordRotateJitter: 2,
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    defaultAccent: YELLOW,
  }),

  // ─── HEADLINE (AUTO CORTES) ───────────────────────────────────────────────
  // Título ESTÁTICO de 1-2 linhas queimado no topo do corte (o "Texto" do
  // Opus Clip). Regras da família: `unit: 'block'` (o título aparece inteiro,
  // não palavra a palavra), `autoEmphasis: false` (quem escolhe a palavra
  // forte é o modelo, no texto), entrada curta e nada de loop — headline que
  // treme rouba a atenção da fala. Cada um muda a ESTRUTURA (caixa por linha ×
  // caixa por bloco × pílula × sem caixa), não só a cor.
  p({
    id: 'hl-caixa-branca',
    name: 'Caixa Branca',
    cat: 'Headline',
    font: 'montserrat800',
    size: 0.058,
    uppercase: false,
    lineHeight: 1.22,
    box: { mode: 'line', fill: '#ffffff', radius: 0.28, padX: 0.5, padY: 0.28, autoText: true },
    unit: 'block',
    in: { kind: 'pop', dur: 260, ease: 'outBackSoft' },
    autoEmphasis: false,
    defaultPrimary: '#111111',
    defaultAccent: '#e0163a',
  }),
  p({
    id: 'hl-caixa-preta',
    name: 'Caixa Preta',
    cat: 'Headline',
    font: 'montserrat800',
    size: 0.054,
    uppercase: true,
    lineHeight: 1.2,
    spacing: 0.01,
    // caixa ÚNICA envolvendo o bloco inteiro (a branca faz uma por linha) e
    // canto reto: silhueta diferente, não só a cor invertida
    box: {
      mode: 'block',
      fill: '#111111',
      radius: 0.06,
      padX: 0.6,
      padY: 0.34,
      autoText: true,
      border: { color: 'rgba(255,255,255,0.28)', width: 0.03 },
    },
    unit: 'block',
    in: { kind: 'fade', dur: 240, ease: 'outQuad' },
    autoEmphasis: false,
    defaultPrimary: '#ffffff',
    defaultAccent: YELLOW,
  }),
  p({
    id: 'hl-marca-texto',
    name: 'Marca-texto',
    cat: 'Headline',
    font: 'inter800',
    size: 0.056,
    uppercase: false,
    lineHeight: 1.16,
    // faixa JUSTA no texto (pad mínimo, canto quase reto) = marca-texto
    box: { mode: 'line', fill: '#ffe34d', radius: 0.08, padX: 0.35, padY: 0.12, autoText: true },
    unit: 'block',
    in: { kind: 'wipe', dur: 280, ease: 'outExpo' },
    autoEmphasis: false,
    defaultPrimary: '#111111',
    defaultAccent: '#e0163a',
  }),
  p({
    id: 'hl-faixa-vermelha',
    name: 'Faixa Vermelha',
    cat: 'Headline',
    font: 'anton',
    size: 0.062,
    uppercase: true,
    lineHeight: 1.1,
    spacing: 0.015,
    box: { mode: 'block', fill: '#e0163a', radius: 0.12, padX: 0.5, padY: 0.3 },
    fill: '#ffffff',
    unit: 'block',
    in: { kind: 'slide-left', dur: 300, ease: 'outExpo', amp: 1 },
    autoEmphasis: false,
    defaultPrimary: '#ffffff',
    defaultAccent: '#ffe34d',
  }),
  p({
    id: 'hl-pilula',
    name: 'Pílula',
    cat: 'Headline',
    font: 'dmsans900',
    size: 0.055,
    uppercase: false,
    lineHeight: 1.34,
    // raio 0.5 = semicírculo nas pontas; fundo translúcido deixa o vídeo passar
    box: { mode: 'line', fill: 'rgba(0,0,0,0.72)', radius: 0.5, padX: 0.7, padY: 0.3 },
    fill: '#ffffff',
    unit: 'block',
    in: { kind: 'rise', dur: 300, ease: 'outQuint', amp: 0.4 },
    autoEmphasis: false,
    defaultPrimary: '#ffffff',
    defaultAccent: '#7cf5c0',
  }),
  p({
    id: 'hl-jornal',
    name: 'Manchete',
    cat: 'Headline',
    font: 'merriweather900',
    size: 0.055,
    uppercase: false,
    lineHeight: 1.24,
    // serifada preta sobre papel branco + fio embaixo = capa de jornal
    box: { mode: 'block', fill: '#f6f4ef', radius: 0.02, padX: 0.55, padY: 0.34, autoText: true },
    bar: { color: '#111111', thickness: 0.035 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint' },
    autoEmphasis: false,
    defaultPrimary: '#111111',
    defaultAccent: '#b3121f',
  }),
  p({
    id: 'hl-gradiente',
    name: 'Gradiente Ouro',
    cat: 'Headline',
    font: 'archivo',
    size: 0.064,
    uppercase: true,
    lineHeight: 1.06,
    // sem caixa: o contraste vem do metal + sombra dura (mesma receita do
    // Título Ouro, sem a tipografia mista que exige palavra destacada)
    fill: 'gradient',
    gradientStops: [
      [0, '#fff8dd'],
      [0.42, '#ffd35c'],
      [0.64, '#c98a12'],
      [0.78, '#f2b02c'],
      [1, '#9a6600'],
    ],
    shine: { period: 2800, alpha: 0.7 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.04, y: 0.055 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    autoEmphasis: false,
    defaultPrimary: '#ffd35c',
    defaultAccent: '#ffffff',
  }),
  p({
    id: 'hl-contorno',
    name: 'Contorno',
    cat: 'Headline',
    font: 'anton',
    size: 0.068,
    uppercase: true,
    lineHeight: 1.02,
    // sem caixa e sem fundo: legibilidade vem do contorno grosso + sombra
    stroke: { color: '#0b0b0c', width: 0.13 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
    unit: 'block',
    in: { kind: 'pop', dur: 260, ease: 'outBack' },
    autoEmphasis: false,
    defaultPrimary: '#ffffff',
    defaultAccent: YELLOW,
  }),
];

// Manuais primeiro (curadoria fina), depois as variantes geradas — os IDs
// gerados têm prefixo 'g-' e nunca colidem com os manuais.
export const TYPO_PRESETS: TypoPreset[] = [...MANUAL_PRESETS, ...GENERATED_PRESETS];

export const TYPO_CATEGORIES: string[] = Array.from(
  new Set(TYPO_PRESETS.map((pr) => pr.cat)),
);

export function getPreset(id: string): TypoPreset {
  return TYPO_PRESETS.find((pr) => pr.id === id) ?? TYPO_PRESETS[0];
}
