/**
 * Catálogo de modelos da Tipografia Automática — 80 letterings animados
 * no espírito dos packs MOGRT de Premiere (in/out por unidade, stagger,
 * overshoot/elastic/bounce, karaokê, glitch de fatias, chroma RGB, extrude
 * 3D, sombra dura de pôster, caixas/barras inclinadas, neon, ouro/chrome
 * com shine sweep, duotone, aura, tamanhos alternados e DESTAQUE AUTOMÁTICO
 * da palavra forte de cada bloco).
 *
 * Cada preset é DATA — o lib/typography/engine.ts implementa as primitivas.
 * defaultPrimary/defaultAccent são o esquema de cor de fábrica; o user pode
 * sobrescrever os dois no editor sem trocar de modelo.
 */

import type { TypoPreset } from './engine';

const WHITE = '#ffffff';
const INK = '#0f0f10';
const YELLOW = '#ffd60a';
const LIME = '#c8e87c';
const CYAN = '#22d3ee';
const PINK = '#f472b6';
const RED = '#ff2d55';
const VIOLET = '#a78bfa';
const ORANGE = '#ff9f0a';
const GREEN_TERM = '#4ade80';

type P = Partial<TypoPreset> & Pick<TypoPreset, 'id' | 'name' | 'cat' | 'font' | 'in'>;

function p(base: P): TypoPreset {
  return {
    size: 0.062,
    uppercase: true,
    lineHeight: 1.16,
    fill: 'primary',
    unit: 'word',
    out: { kind: 'none', dur: 0 },
    highlightStyle: 'color',
    defaultPrimary: WHITE,
    defaultAccent: YELLOW,
    ...base,
  } as TypoPreset;
}

export const TYPO_PRESETS: TypoPreset[] = [
  // ─── VIRAL (tipografia mista, refs validadas pelo user) ──────────────────
  p({
    id: 'titulo-viral',
    name: 'Título Viral',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.045 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.045, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.44, lowercase: true },
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 90, amp: 0.6 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'titulo-ouro',
    name: 'Título Ouro',
    cat: 'Viral',
    font: 'anton',
    size: 0.08,
    lineHeight: 1.0,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3c4'],
      [0.4, '#ffcd3c'],
      [0.62, '#c98a12'],
      [0.75, '#f2b02c'],
      [1, '#8f5e00'],
    ],
    shine: { period: 2600, alpha: 0.75 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.42, lowercase: true },
    in: { kind: 'rise', dur: 320, ease: 'outQuint', stagger: 100, amp: 0.6 },
    autoEmphasis: true,
    defaultAccent: '#ffcd3c',
  }),
  p({
    id: 'viral-clean',
    name: 'Essa Forma',
    cat: 'Viral',
    font: 'archivo',
    size: 0.074,
    lineHeight: 1.02,
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.04, y: 0.05 },
    mix: { font: 'caveat700', scale: 0.72, lowercase: true, accentLast: true },
    in: { kind: 'pop', dur: 280, ease: 'outBackSoft', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: ORANGE,
  }),
  p({
    id: 'neon-viral',
    name: 'Neon Viral',
    cat: 'Viral',
    font: 'bebas',
    size: 0.086,
    lineHeight: 1.0,
    spacing: 0.02,
    glow: { color: 'accent', blur: 0.55 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.04 },
    mix: { font: 'playfair900i', scale: 0.42, lowercase: true },
    in: { kind: 'fade', dur: 260, ease: 'outQuad', stagger: 90 },
    autoEmphasis: true,
    defaultAccent: PINK,
  }),
  p({
    id: 'contraste',
    name: 'Contraste',
    cat: 'Viral',
    font: 'montserrat900',
    size: 0.07,
    lineHeight: 1.04,
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    mix: { font: 'playfair900i', scale: 0.52, lowercase: true, color: 'accent' },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 90 },
    autoEmphasis: true,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'revista',
    name: 'Revista',
    cat: 'Viral',
    font: 'playfair900',
    size: 0.072,
    lineHeight: 1.04,
    uppercase: false,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    mix: { font: 'oswald600', scale: 0.46 },
    in: { kind: 'mask-up', dur: 400, ease: 'outQuint', stagger: 110 },
    autoEmphasis: true,
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'linha-destaque',
    name: 'Linha Rosa',
    cat: 'Viral',
    font: 'oswald600',
    size: 0.064,
    lineHeight: 1.12,
    lineAccent: 'last',
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.03, y: 0.04 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 110 },
    autoEmphasis: false,
    defaultAccent: PINK,
  }),
  p({
    id: 'manuscrito',
    name: 'Manuscrito',
    cat: 'Viral',
    font: 'caveat700',
    size: 0.078,
    uppercase: false,
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.03, y: 0.05 },
    in: { kind: 'rise', dur: 340, ease: 'outBackSoft', stagger: 100, amp: 0.5 },
    autoEmphasis: true,
    highlightScale: 1.25,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'escada',
    name: 'Escada',
    cat: 'Viral',
    font: 'anton',
    size: 0.06,
    lineHeight: 1.05,
    sizeCycle: [0.78, 1.02, 1.34],
    colorCycle: ['primary', 'primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'esmagado',
    name: 'Esmagado',
    cat: 'Viral',
    font: 'archivo',
    size: 0.06,
    lineHeight: 1.04,
    sizeCycle: [1.42, 0.74],
    colorCycle: ['accent', 'primary'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'squash', dur: 280, ease: 'outBack', stagger: 100 },
    defaultAccent: ORANGE,
  }),

  // ─── PREMIUM ──────────────────────────────────────────────────────────────
  p({
    id: 'auto-hype',
    name: 'Auto Hype',
    cat: 'Premium',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 80 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    autoEmphasis: true,
    highlightScale: 1.42,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'ouro',
    name: 'Ouro',
    cat: 'Premium',
    font: 'anton',
    size: 0.072,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff8dc'],
      [0.3, '#ffe08a'],
      [0.52, '#f0b429'],
      [0.62, '#8a5a00'],
      [0.72, '#e8a824'],
      [1, '#6b4300'],
    ],
    shine: { period: 2400, alpha: 0.8 },
    stroke: { color: '#4a3200', width: 0.05 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 320, ease: 'outQuint', amp: 0.9 },
    defaultAccent: '#ffd970',
  }),
  p({
    id: 'chrome',
    name: 'Chrome',
    cat: 'Premium',
    font: 'archivo',
    size: 0.066,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.42, '#dfe6ee'],
      [0.52, '#8d99a6'],
      [0.6, '#eef3f8'],
      [1, '#7a8794'],
    ],
    shine: { period: 2000, alpha: 0.9 },
    stroke: { color: '#232830', width: 0.06 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.08 },
    in: { kind: 'drop', dur: 300, ease: 'outBack', stagger: 90, amp: 1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'brilho',
    name: 'Brilho',
    cat: 'Premium',
    font: 'inter800',
    size: 0.058,
    shine: { period: 1700, alpha: 0.9 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    in: { kind: 'rise', dur: 300, ease: 'outQuint', stagger: 60, amp: 0.6 },
    out: { kind: 'fade', dur: 160 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'long-shadow',
    name: 'Long Shadow',
    cat: 'Premium',
    font: 'montserrat900',
    size: 0.064,
    extrude: { color: 'rgba(0,0,0,0.4)', x: 0.09, y: 0.09, steps: 12, fade: true },
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 80 },
    autoEmphasis: true,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'duotone',
    name: 'Duotone',
    cat: 'Premium',
    font: 'anton',
    size: 0.074,
    fill: 'gradient',
    gradientStops: [
      [0, 'primary'],
      [0.5, 'primary'],
      [0.505, 'accent'],
      [1, 'accent'],
    ],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'stretch-x', dur: 300, ease: 'outBack', amp: 1.2 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'metal-slam',
    name: 'Metal Slam',
    cat: 'Premium',
    font: 'anton',
    size: 0.078,
    fill: 'gradient',
    gradientStops: [
      [0, '#f8fafc'],
      [0.45, '#cbd5e1'],
      [0.52, '#64748b'],
      [0.6, '#e2e8f0'],
      [1, '#475569'],
    ],
    shine: { period: 2600, alpha: 0.75 },
    chroma: { amp: 0.016 },
    hardShadow: { color: 'rgba(0,0,0,0.6)', x: 0.06, y: 0.09 },
    unit: 'block',
    in: { kind: 'zoom-out', dur: 240, ease: 'outQuint', amp: 2 },
    out: { kind: 'zoom', dur: 140 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'ouro-editorial',
    name: 'Ouro Editorial',
    cat: 'Premium',
    font: 'playfair900',
    size: 0.062,
    uppercase: false,
    fill: 'gradient',
    gradientStops: [
      [0, '#fdf3d0'],
      [0.45, '#eac859'],
      [0.6, '#9c7410'],
      [0.72, '#e3b93e'],
      [1, '#7a5a08'],
    ],
    shine: { period: 3200, alpha: 0.65 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
    unit: 'block',
    in: { kind: 'blur-zoom', dur: 480, ease: 'outQuint', amp: 0.9 },
    out: { kind: 'fade', dur: 240 },
    defaultAccent: '#eac859',
  }),

  // ─── COR ──────────────────────────────────────────────────────────────────
  p({
    id: 'fogo',
    name: 'Fogo',
    cat: 'Cor',
    font: 'anton',
    size: 0.072,
    fill: 'gradient',
    gradientStops: [
      [0, '#fff3b0'],
      [0.4, '#ffb703'],
      [0.75, '#fb5607'],
      [1, '#d00000'],
    ],
    glow: { color: '#ff7b00', blur: 0.4 },
    loop: { kind: 'flicker', amp: 0.3, freq: 10 },
    in: { kind: 'squash', dur: 280, ease: 'outBack', stagger: 90 },
    defaultAccent: '#ffb703',
  }),
  p({
    id: 'gelo',
    name: 'Gelo',
    cat: 'Cor',
    font: 'archivo',
    size: 0.066,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffffff'],
      [0.55, '#bde0fe'],
      [1, '#4cc9f0'],
    ],
    aura: { color: '#4cc9f0', count: 3, width: 0.16, alpha: 0.35 },
    in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 80, amp: 1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'sunset',
    name: 'Sunset',
    cat: 'Cor',
    font: 'nunito900',
    size: 0.064,
    fill: 'gradient',
    gradientStops: [
      [0, '#ffd6ff'],
      [0.5, '#ff8fab'],
      [1, '#ff5d8f'],
    ],
    stroke: { color: '#5a1836', width: 0.08 },
    loop: { kind: 'wave', amp: 0.06, freq: 1.3 },
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.7 },
    defaultAccent: '#ff8fab',
  }),
  p({
    id: 'carnaval',
    name: 'Carnaval',
    cat: 'Cor',
    font: 'nunito900',
    size: 0.062,
    colorCycle: [YELLOW, CYAN, PINK, LIME],
    stroke: { color: INK, width: 0.15 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.07 },
    wordRotateJitter: 2.5,
    in: { kind: 'pop', dur: 300, ease: 'outBack', stagger: 90 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'tamanhos',
    name: 'Tamanhos',
    cat: 'Cor',
    font: 'anton',
    size: 0.06,
    lineHeight: 1.06,
    sizeCycle: [0.82, 1.3, 1],
    colorCycle: ['primary', 'accent', 'primary'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'gigante',
    name: 'Gigante',
    cat: 'Cor',
    font: 'archivo',
    size: 0.058,
    lineHeight: 1.04,
    sizeCycle: [1, 1.45],
    colorCycle: ['primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.07 },
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 100, amp: 1.2 },
    defaultAccent: ORANGE,
  }),
  p({
    id: 'split-pop',
    name: 'Split Pop',
    cat: 'Cor',
    font: 'anton',
    size: 0.07,
    fill: 'gradient',
    gradientStops: [
      [0, 'primary'],
      [0.5, 'primary'],
      [0.505, 'accent'],
      [1, 'accent'],
    ],
    stroke: { color: INK, width: 0.09 },
    wordRotateJitter: 2,
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 90 },
    defaultAccent: CYAN,
  }),

  // ─── IMPACTO ──────────────────────────────────────────────────────────────
  p({
    id: 'pop-punch',
    autoEmphasis: true,
    name: 'Pop Punch',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.066,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 70 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.07 },
  }),
  p({
    id: 'extrude-slam',
    name: '3D Slam',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.068,
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', stagger: 80, amp: 1.4 },
    extrude: { color: 'accent', x: 0.055, y: 0.065, steps: 6 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.1, y: 0.12 },
    blockRotate: -2,
    defaultAccent: '#b45309',
  }),
  p({
    id: 'stomp',
    autoEmphasis: true,
    name: 'Stomp',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.07,
    in: { kind: 'drop', dur: 300, ease: 'bounce', stagger: 90, amp: 1.4 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.09 },
    blockRotate: -1.5,
  }),
  p({
    id: 'carimbo',
    autoEmphasis: true,
    name: 'Carimbo',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 180, ease: 'outQuint', amp: 2.2 },
    stroke: { color: 'accent', width: 0.1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.05, y: 0.06 },
    blockRotateJitter: 4,
    defaultAccent: RED,
  }),
  p({
    id: 'barra-impacto',
    autoEmphasis: true,
    name: 'Barra de Impacto',
    cat: 'Impacto',
    font: 'oswald600',
    size: 0.068,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'wipe', dur: 380, ease: 'outExpo', stagger: 90 },
    bar: { color: 'accent', thickness: 0.16, skew: -10 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
    defaultAccent: RED,
  }),
  p({
    id: 'zoom-crush',
    autoEmphasis: true,
    name: 'Zoom Crush',
    cat: 'Impacto',
    font: 'anton',
    size: 0.082,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 1.9 },
    out: { kind: 'zoom', dur: 140 },
    stroke: { color: INK, width: 0.12 },
    chroma: { amp: 0.022 },
  }),
  p({
    id: 'slam-giro',
    autoEmphasis: true,
    name: 'Slam Giro',
    cat: 'Impacto',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'rotate-in', dur: 320, ease: 'outBack', stagger: 80, amp: 0.9 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.06, y: 0.07 },
  }),
  p({
    id: 'soco-alternado',
    autoEmphasis: true,
    name: 'Soco Alternado',
    cat: 'Impacto',
    font: 'montserrat900',
    size: 0.068,
    in: { kind: 'squash', dur: 260, ease: 'outBack', stagger: 110 },
    stroke: { color: INK, width: 0.16 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),

  // ─── KARAOKÊ ──────────────────────────────────────────────────────────────
  p({
    id: 'karaoke-fill',
    name: 'Karaokê Fill',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.06,
    karaoke: 'fill',
    unit: 'block',
    in: { kind: 'fade', dur: 140 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: LIME,
  }),
  p({
    id: 'palavra-box',
    name: 'Palavra Box',
    cat: 'Karaokê',
    font: 'inter800',
    size: 0.056,
    karaoke: 'word-box',
    unit: 'block',
    in: { kind: 'rise', dur: 200, ease: 'outCubic', amp: 0.45 },
    box: { mode: 'none', fill: 'accent', radius: 0.18, padX: 0.22, padY: 0.14, skew: -6, shadow: { color: 'rgba(0,0,0,0.45)', x: 0.06, y: 0.08 } },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'palavra-cor',
    name: 'Palavra Cor',
    cat: 'Karaokê',
    font: 'montserrat900',
    size: 0.062,
    karaoke: 'word-color',
    unit: 'block',
    in: { kind: 'pop', dur: 200, ease: 'outBackSoft' },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'karaoke-zoom',
    name: 'Karaokê Zoom',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.06,
    karaoke: 'word-zoom',
    unit: 'block',
    in: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'um-por-um',
    autoEmphasis: true,
    name: 'Um Por Um',
    cat: 'Karaokê',
    font: 'anton',
    size: 0.095,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'pop', dur: 150, ease: 'outBack' },
    stroke: { color: INK, width: 0.11 },
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0, y: 0.08 },
    blockRotateJitter: 2.5,
  }),
  p({
    id: 'solo-box',
    autoEmphasis: true,
    name: 'Solo Box',
    cat: 'Karaokê',
    font: 'archivo',
    size: 0.08,
    karaoke: 'solo',
    unit: 'block',
    in: { kind: 'squash', dur: 200, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.16, padX: 0.4, padY: 0.22, skew: -7, autoText: true, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.11 } },
    blockRotateJitter: 3.5,
    highlightColor: YELLOW,
    defaultAccent: RED,
  }),
  p({
    id: 'sublinha-ativa',
    name: 'Sublinha Ativa',
    cat: 'Karaokê',
    font: 'poppins800',
    size: 0.058,
    karaoke: 'word-underline',
    unit: 'block',
    in: { kind: 'rise', dur: 220, ease: 'outCubic', amp: 0.5 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
    defaultAccent: LIME,
  }),

  // ─── GLITCH ───────────────────────────────────────────────────────────────
  p({
    id: 'glitch-brutal',
    autoEmphasis: true,
    name: 'Glitch Brutal',
    cat: 'Glitch',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'glitch', dur: 420, ease: 'outCubic', amp: 1.6 },
    chroma: { amp: 0.045, flicker: true },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    hardShadow: { color: 'rgba(0,0,0,0.5)', x: 0.04, y: 0.05 },
  }),
  p({
    id: 'glitch-rgb',
    autoEmphasis: true,
    name: 'Glitch RGB',
    cat: 'Glitch',
    font: 'archivo',
    size: 0.064,
    in: { kind: 'glitch', dur: 420, ease: 'outQuad', stagger: 60, amp: 1.2 },
    chroma: { amp: 0.028 },
    glitchBands: true,
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
  }),
  p({
    id: 'glitch-digital',
    autoEmphasis: true,
    name: 'Glitch Digital',
    cat: 'Glitch',
    font: 'anton',
    size: 0.072,
    unit: 'block',
    in: { kind: 'glitch', dur: 360, ease: 'outCubic', amp: 1.6 },
    glitchBands: true,
    loop: { kind: 'glitch', amp: 1, freq: 1 },
    stroke: { color: INK, width: 0.1 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'vhs',
    autoEmphasis: true,
    name: 'VHS',
    cat: 'Glitch',
    font: 'inter800',
    size: 0.056,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'fade', dur: 200 },
    chroma: { amp: 0.05, flicker: true },
    loop: { kind: 'float', amp: 0.04, freq: 0.7 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0 },
  }),
  p({
    id: 'static-pop',
    autoEmphasis: true,
    name: 'Static Pop',
    cat: 'Glitch',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'pop', dur: 180, ease: 'outQuint', stagger: 60 },
    chroma: { amp: 0.03, flicker: true },
    loop: { kind: 'flicker', amp: 0.25, freq: 9 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: RED,
  }),

  // ─── DESTAQUE ─────────────────────────────────────────────────────────────
  p({
    id: 'poster-stack',
    autoEmphasis: true,
    name: 'Pôster',
    cat: 'Destaque',
    font: 'anton',
    size: 0.062,
    lineHeight: 1.02,
    unit: 'block',
    in: { kind: 'mask-up', dur: 340, ease: 'outQuint', stagger: 100 },
    highlightScale: 1.5,
    hardShadow: { color: 'rgba(0,0,0,0.55)', x: 0.05, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-solida',
    autoEmphasis: true,
    name: 'Caixa Sólida',
    cat: 'Destaque',
    font: 'montserrat900',
    size: 0.058,
    unit: 'block',
    in: { kind: 'pop', dur: 260, ease: 'outBack' },
    box: { mode: 'block', fill: 'accent', radius: 0.2, padX: 0.5, padY: 0.3, skew: -4, shadow: { color: 'rgba(0,0,0,0.5)', x: 0.09, y: 0.1 } },
    fill: '#0f0f10',
    highlightColor: RED,
    defaultPrimary: INK,
    defaultAccent: YELLOW,
  }),
  p({
    id: 'caixa-branca',
    autoEmphasis: true,
    name: 'Caixa Branca',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.054,
    unit: 'block',
    in: { kind: 'rise', dur: 260, ease: 'outBackSoft', amp: 0.5 },
    box: { mode: 'line', fill: '#ffffff', radius: 0.18, padX: 0.4, padY: 0.18, shadow: { color: 'rgba(0,0,0,0.35)', x: 0, y: 0.08 } },
    fill: '#111111',
    defaultPrimary: '#111111',
    defaultAccent: RED,
  }),
  p({
    id: 'empilhado',
    autoEmphasis: true,
    name: 'Empilhado',
    cat: 'Destaque',
    font: 'archivo',
    size: 0.054,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 100 },
    box: { mode: 'word', fill: '#111111', radius: 0.1, padX: 0.26, padY: 0.18, skew: -5, autoText: true, cycle: ['accent', '#141414', '#ffffff'], shadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.08 } },
    wordRotateJitter: 2.5,
    defaultAccent: RED,
  }),
  p({
    id: 'adesivo',
    autoEmphasis: true,
    name: 'Adesivo',
    cat: 'Destaque',
    font: 'nunito900',
    size: 0.062,
    in: { kind: 'pop', dur: 480, ease: 'elastic', stagger: 100 },
    fill: 'accent',
    stroke: { color: '#ffffff', width: 0.26 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0.06, y: 0.09 },
    wordRotateJitter: 3,
    highlightColor: YELLOW,
    defaultAccent: PINK,
  }),
  p({
    id: 'tarja-preta',
    autoEmphasis: true,
    name: 'Tarja Preta',
    cat: 'Destaque',
    font: 'oswald600',
    size: 0.06,
    unit: 'block',
    in: { kind: 'wipe', dur: 360, ease: 'outExpo', stagger: 80 },
    box: { mode: 'line', fill: 'rgba(0,0,0,0.85)', radius: 0.04, padX: 0.4, padY: 0.14, skew: -4 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chip-palavra',
    autoEmphasis: true,
    name: 'Chip Palavra',
    cat: 'Destaque',
    font: 'poppins800',
    size: 0.05,
    in: { kind: 'pop', dur: 240, ease: 'outBack', stagger: 90 },
    box: { mode: 'word', fill: 'rgba(0,0,0,0.8)', radius: 0.3, padX: 0.3, padY: 0.2 },
    defaultAccent: LIME,
    highlightStyle: 'box',
  }),
  p({
    id: 'auto-box',
    name: 'Auto Box',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.056,
    in: { kind: 'rise', dur: 260, ease: 'outCubic', stagger: 70, amp: 0.45 },
    autoEmphasis: true,
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.05 },
    defaultAccent: LIME,
  }),
  p({
    id: 'marca-texto',
    autoEmphasis: true,
    name: 'Marca-Texto',
    cat: 'Destaque',
    font: 'inter800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 280, ease: 'outCubic', stagger: 70, amp: 0.4 },
    highlightStyle: 'box',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'sublinhado-forte',
    autoEmphasis: true,
    name: 'Sublinhado',
    cat: 'Destaque',
    font: 'montserrat800',
    size: 0.056,
    uppercase: false,
    in: { kind: 'fade', dur: 260, ease: 'outQuad', stagger: 60 },
    highlightStyle: 'underline',
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: LIME,
  }),

  // ─── MINIMAL ──────────────────────────────────────────────────────────────
  p({
    id: 'fade-limpo',
    autoEmphasis: true,
    name: 'Fade Limpo',
    cat: 'Minimal',
    font: 'inter800',
    size: 0.052,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 320, ease: 'outQuad' },
    out: { kind: 'fade', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'sobe-suave',
    autoEmphasis: true,
    name: 'Sobe Suave',
    cat: 'Minimal',
    font: 'poppins800',
    size: 0.054,
    uppercase: false,
    in: { kind: 'rise', dur: 340, ease: 'outQuint', stagger: 60, amp: 0.7 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'tracking-aberto',
    autoEmphasis: true,
    name: 'Tracking Aberto',
    cat: 'Minimal',
    font: 'montserrat800',
    size: 0.05,
    spacing: 0.06,
    unit: 'block',
    in: { kind: 'tracking-in', dur: 420, ease: 'outExpo', amp: 0.7 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'oswald-clean',
    autoEmphasis: true,
    name: 'Alto e Limpo',
    cat: 'Minimal',
    font: 'oswald600',
    size: 0.062,
    spacing: 0.02,
    unit: 'block',
    in: { kind: 'blur', dur: 300, ease: 'outCubic', amp: 0.8 },
    out: { kind: 'blur', dur: 180 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.14, x: 0, y: 0.05 },
  }),

  // ─── BOUNCE ───────────────────────────────────────────────────────────────
  p({
    id: 'bounce-elastico',
    autoEmphasis: true,
    name: 'Bounce Elástico',
    cat: 'Bounce',
    font: 'poppins800',
    size: 0.062,
    in: { kind: 'pop', dur: 560, ease: 'elastic', stagger: 90 },
    stroke: { color: INK, width: 0.13 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
    defaultAccent: PINK,
  }),
  p({
    id: 'jelly',
    autoEmphasis: true,
    name: 'Jelly',
    cat: 'Bounce',
    font: 'nunito900',
    size: 0.064,
    in: { kind: 'squash', dur: 420, ease: 'elastic', stagger: 100 },
    stroke: { color: INK, width: 0.15 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'quica-letra',
    autoEmphasis: true,
    name: 'Quica Letra',
    cat: 'Bounce',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'drop', dur: 340, ease: 'bounce', stagger: 26, amp: 1.1 },
    stroke: { color: INK, width: 0.14 },
    hardShadow: { color: 'rgba(0,0,0,0.4)', x: 0, y: 0.06 },
  }),

  // ─── MÁQUINA ──────────────────────────────────────────────────────────────
  p({
    id: 'maquina',
    autoEmphasis: true,
    name: 'Máquina',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.05,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 900 },
    caret: 'bar',
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.1, x: 0, y: 0.03 },
    defaultAccent: WHITE,
  }),
  p({
    id: 'terminal',
    autoEmphasis: true,
    name: 'Terminal',
    cat: 'Máquina',
    font: 'jetbrains700',
    size: 0.048,
    uppercase: false,
    unit: 'block',
    in: { kind: 'typewriter', dur: 800 },
    caret: 'block',
    fill: '#4ade80',
    glow: { color: GREEN_TERM, blur: 0.5 },
    defaultPrimary: GREEN_TERM,
    defaultAccent: GREEN_TERM,
  }),
  p({
    id: 'digitada',
    autoEmphasis: true,
    name: 'Digitada',
    cat: 'Máquina',
    font: 'inter800',
    size: 0.054,
    uppercase: true,
    unit: 'block',
    in: { kind: 'typewriter', dur: 620 },
    caret: 'bar',
    box: { mode: 'line', fill: 'rgba(0,0,0,0.72)', radius: 0.16, padX: 0.34, padY: 0.16 },
    defaultAccent: ORANGE,
  }),

  // ─── FOCO ─────────────────────────────────────────────────────────────────
  p({
    id: 'blur-reveal',
    autoEmphasis: true,
    name: 'Blur Reveal',
    cat: 'Foco',
    font: 'poppins800',
    size: 0.058,
    in: { kind: 'blur', dur: 380, ease: 'outCubic', stagger: 80, amp: 1 },
    out: { kind: 'blur', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'foco-cine',
    autoEmphasis: true,
    name: 'Foco Cine',
    cat: 'Foco',
    font: 'playfair900',
    size: 0.06,
    uppercase: false,
    unit: 'block',
    in: { kind: 'blur-zoom', dur: 520, ease: 'outQuint', amp: 1 },
    out: { kind: 'blur', dur: 260 },
    shadow: { color: 'rgba(0,0,0,0.55)', blur: 0.16, x: 0, y: 0.05 },
  }),
  p({
    id: 'motion-slide',
    autoEmphasis: true,
    name: 'Motion Slide',
    cat: 'Foco',
    font: 'inter800',
    size: 0.056,
    in: { kind: 'slide-left', dur: 300, ease: 'outExpo', stagger: 55, amp: 1 },
    out: { kind: 'fade', dur: 150 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),

  // ─── REVEAL ───────────────────────────────────────────────────────────────
  p({
    id: 'mask-up',
    autoEmphasis: true,
    name: 'Mask Up',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.06,
    unit: 'block',
    in: { kind: 'mask-up', dur: 380, ease: 'outQuint', stagger: 110 },
    out: { kind: 'fade', dur: 160 },
    shadow: { color: 'rgba(0,0,0,0.4)', blur: 0.1, x: 0, y: 0.03 },
  }),
  p({
    id: 'cortina',
    autoEmphasis: true,
    name: 'Cortina',
    cat: 'Reveal',
    font: 'anton',
    size: 0.07,
    unit: 'block',
    in: { kind: 'wipe', dur: 420, ease: 'outExpo', stagger: 90 },
    out: { kind: 'fade', dur: 160 },
    stroke: { color: INK, width: 0.1 },
  }),
  p({
    id: 'flip-belt',
    autoEmphasis: true,
    name: 'Flip 3D',
    cat: 'Reveal',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'flip', dur: 340, ease: 'outBack', stagger: 90 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: ORANGE,
  }),
  p({
    id: 'stretch-impact',
    autoEmphasis: true,
    name: 'Stretch',
    cat: 'Reveal',
    font: 'anton',
    size: 0.074,
    unit: 'block',
    in: { kind: 'stretch-x', dur: 320, ease: 'outBack', amp: 1.6 },
    stroke: { color: INK, width: 0.11 },
  }),
  p({
    id: 'skew-kinetic',
    autoEmphasis: true,
    name: 'Skew Kinetic',
    cat: 'Reveal',
    font: 'poppins800',
    size: 0.06,
    in: { kind: 'skew-slide', dur: 300, ease: 'outExpo', stagger: 70 },
    out: { kind: 'fade', dur: 140 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0.03, y: 0.05 },
  }),

  // ─── NEON ─────────────────────────────────────────────────────────────────
  p({
    id: 'neon-brutal',
    autoEmphasis: true,
    name: 'Neon Brutal',
    cat: 'Neon',
    font: 'bebas',
    size: 0.086,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 240, ease: 'outQuint', amp: 0.9 },
    glow: { color: 'accent', blur: 0.65 },
    stroke: { color: '#ffffff', width: 0.045 },
    chroma: { amp: 0.02, flicker: true },
    loop: { kind: 'flicker', amp: 0.5, freq: 12 },
    defaultAccent: PINK,
  }),
  p({
    id: 'eco-neon',
    autoEmphasis: true,
    name: 'Eco Neon',
    cat: 'Neon',
    font: 'bebas',
    size: 0.082,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'fade', dur: 240, ease: 'outQuad' },
    aura: { color: 'accent', count: 4, width: 0.24, alpha: 0.5, pulse: true },
    glow: { color: 'accent', blur: 0.4 },
    defaultAccent: VIOLET,
  }),
  p({
    id: 'auto-neon',
    name: 'Neon Destaque',
    cat: 'Neon',
    font: 'bebas',
    size: 0.08,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 260, ease: 'outQuint', amp: 0.8 },
    glow: { color: 'accent', blur: 0.55 },
    autoEmphasis: true,
    highlightColor: '#ffffff',
    highlightScale: 1.2,
    loop: { kind: 'flicker', amp: 0.35, freq: 10 },
    defaultAccent: PINK,
  }),
  p({
    id: 'neon-pulse',
    autoEmphasis: true,
    name: 'Neon Pulse',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    unit: 'block',
    in: { kind: 'fade', dur: 260, ease: 'outQuad' },
    loop: { kind: 'flicker', amp: 0.55, freq: 11 },
    glow: { color: 'accent', blur: 0.55 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'neon-rosa',
    autoEmphasis: true,
    name: 'Neon Rosa',
    cat: 'Neon',
    font: 'bebas',
    size: 0.078,
    spacing: 0.03,
    in: { kind: 'pop', dur: 260, ease: 'outBackSoft', stagger: 80 },
    glow: { color: 'accent', blur: 0.5 },
    loop: { kind: 'pulse', amp: 0.05, freq: 1.6 },
    defaultAccent: PINK,
  }),
  p({
    id: 'luz-de-palco',
    autoEmphasis: true,
    name: 'Luz de Palco',
    cat: 'Neon',
    font: 'anton',
    size: 0.08,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 300, ease: 'outQuint', amp: 0.8 },
    glow: { color: 'accent', blur: 0.7 },
    loop: { kind: 'pulse', amp: 0.04, freq: 1.1 },
    defaultAccent: YELLOW,
  }),

  // ─── KINETIC ──────────────────────────────────────────────────────────────
  p({
    id: 'duas-cores',
    name: 'Duas Cores',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.062,
    in: { kind: 'skew-slide', dur: 280, ease: 'outExpo', stagger: 80 },
    colorCycle: ['primary', 'accent'],
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.045, y: 0.06 },
    defaultAccent: YELLOW,
  }),
  p({
    id: 'chroma-wave',
    autoEmphasis: true,
    name: 'Chroma Wave',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    chroma: { amp: 0.035 },
    loop: { kind: 'wave', amp: 0.07, freq: 1.4 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'onda',
    autoEmphasis: true,
    name: 'Onda',
    cat: 'Kinetic',
    font: 'nunito900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'rise', dur: 300, ease: 'outBackSoft', stagger: 24, amp: 0.8 },
    loop: { kind: 'wave', amp: 0.09, freq: 1.6 },
    stroke: { color: INK, width: 0.13 },
    defaultAccent: CYAN,
  }),
  p({
    id: 'shake-hype',
    autoEmphasis: true,
    name: 'Shake Hype',
    cat: 'Kinetic',
    font: 'archivo',
    size: 0.066,
    unit: 'block',
    in: { kind: 'zoom-out', dur: 220, ease: 'outQuint', amp: 1 },
    loop: { kind: 'shake', amp: 0.05, freq: 8 },
    stroke: { color: INK, width: 0.12 },
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0, y: 0.07 },
    defaultAccent: RED,
  }),
  p({
    id: 'float-suave',
    autoEmphasis: true,
    name: 'Float Suave',
    cat: 'Kinetic',
    font: 'poppins800',
    size: 0.056,
    uppercase: false,
    unit: 'block',
    in: { kind: 'rise', dur: 380, ease: 'outQuint', amp: 0.6 },
    loop: { kind: 'float', amp: 0.05, freq: 0.9 },
    out: { kind: 'fade', dur: 200 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.04 },
  }),
  p({
    id: 'letra-viva',
    autoEmphasis: true,
    name: 'Letra Viva',
    cat: 'Kinetic',
    font: 'montserrat900',
    size: 0.06,
    unit: 'char',
    in: { kind: 'pop', dur: 260, ease: 'outBack', stagger: 22 },
    loop: { kind: 'wave', amp: 0.05, freq: 1.2 },
    stroke: { color: INK, width: 0.14 },
    defaultAccent: LIME,
  }),

  // ─── EDITORIAL ────────────────────────────────────────────────────────────
  p({
    id: 'editorial-destaque',
    autoEmphasis: true,
    name: 'Editorial Destaque',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'mask-up', dur: 420, ease: 'outQuint', stagger: 120 },
    highlightScale: 1.32,
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
    defaultAccent: '#e8c66b',
  }),
  p({
    id: 'editorial-serif',
    autoEmphasis: true,
    name: 'Editorial',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.058,
    uppercase: false,
    unit: 'block',
    in: { kind: 'fade', dur: 420, ease: 'outQuad' },
    out: { kind: 'fade', dur: 240 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'vogue-mask',
    autoEmphasis: true,
    name: 'Vogue',
    cat: 'Editorial',
    font: 'playfair900',
    size: 0.06,
    uppercase: true,
    spacing: 0.04,
    unit: 'block',
    in: { kind: 'mask-up', dur: 460, ease: 'outQuint', stagger: 130 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.45)', blur: 0.12, x: 0, y: 0.03 },
  }),
  p({
    id: 'citacao',
    autoEmphasis: true,
    name: 'Citação',
    cat: 'Editorial',
    font: 'playfair900i',
    size: 0.056,
    uppercase: false,
    in: { kind: 'rise', dur: 380, ease: 'outQuint', stagger: 80, amp: 0.5 },
    out: { kind: 'fade', dur: 220 },
    shadow: { color: 'rgba(0,0,0,0.5)', blur: 0.14, x: 0, y: 0.04 },
  }),
  p({
    id: 'rabisco',
    autoEmphasis: true,
    name: 'Rabisco',
    cat: 'Editorial',
    font: 'marker',
    size: 0.06,
    uppercase: false,
    in: { kind: 'rotate-in', dur: 300, ease: 'outBack', stagger: 100, amp: 0.5 },
    wordRotateJitter: 2,
    hardShadow: { color: 'rgba(0,0,0,0.45)', x: 0.04, y: 0.06 },
    defaultAccent: YELLOW,
  }),
];

export const TYPO_CATEGORIES: string[] = Array.from(
  new Set(TYPO_PRESETS.map((pr) => pr.cat)),
);

export function getPreset(id: string): TypoPreset {
  return TYPO_PRESETS.find((pr) => pr.id === id) ?? TYPO_PRESETS[0];
}
